In [1]:
import torch
import pickle
import numpy as np
import pandas as pd
import os
import json 
from os.path import dirname



root_path = dirname(os.getcwd()) + "/AdaTest"

pd.set_option("display.max_columns", None)
# data_dir = root_path + "/data/datasets/original/"
data_dir_processed = root_path + "/data/datasets/comuzzi/_processed/"
data_dir_graphs = root_path + "/data/datasets/comuzzi/graphs_repair/"

print(root_path, data_dir_processed, data_dir_graphs, sep="\n")

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
#device = "cpu"

/home/sebastiano.dissegna/AdaTest
/home/sebastiano.dissegna/AdaTest/data/datasets/comuzzi/_processed/
/home/sebastiano.dissegna/AdaTest/data/datasets/comuzzi/graphs_repair/

In [ ]:
#ACT_TIME_ONLY = True

In [2]:
ACT_TIME_ONLY = False

In [3]:
with open("data/dataset_features.json", 'r') as file:
    datasets_info = json.load(file)

In [4]:
list(datasets_info.keys())

['BPI_Challenge_2013_open_problems',
 'sp2020',
 'Helpdesk',
 'BPI20_RequestForPayment',
 'BPI Challenge 2017 - Offer log',
 'BPI_Challenge_2012_W_Complete',
 'BPI_Challenge_2012_A',
 'bpi_2012_CZ',
 'bpi_2013_CZ',
 'large_log_CZ',
 'small_log_CZ',
 'sp2020_CZ',
 'BPI20_RequestForPayment_CZ']

In [5]:
dataset = "BPI20_RequestForPayment_CZ"

In [6]:
with open("data/dataset_features.json", 'r') as file:
    dataset_info = json.load(file)[dataset]

In [7]:
tab_all = pd.read_csv(f"{data_dir_processed}/{dataset}/{dataset}_processed_all.csv") 
tab_all.head()

,CaseID,Activity,time:timestamp,org:resource,org:role,case:Project,case:Task,case:OrganizationalEntity,case:Cost Type,case:RequestedAmount,case:Activity,case:RfpNumber
0,1,Request For Payment SUBMITTED by EMPLOYEE,0.000000,STAFF MEMBER,EMPLOYEE,project 148216,UNKNOWN,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
1,1,Request For Payment FINAL_APPROVED by SUPERVISOR,3.761200,STAFF MEMBER,SUPERVISOR,project 148216,UNKNOWN,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
2,1,Request For Payment REJECTED by MISSING,11.499992,STAFF MEMBER,MISSING,project 148216,UNKNOWN,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
3,1,Request For Payment SUBMITTED by EMPLOYEE,15.337479,STAFF MEMBER,EMPLOYEE,project 148216,UNKNOWN,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215
4,1,Request For Payment APPROVED by PRE_APPROVER,15.337486,STAFF MEMBER,PRE_APPROVER,project 148216,UNKNOWN,organizational unit 65463,0,34.336343,UNKNOWN,request for payment number 148215

In [8]:
print(f"number of events {len(tab_all)}")
print(f"number of traces {len(tab_all['CaseID'].unique())}")
print(f"number of attributes {len(tab_all.columns) - 1}")

number of events 36796
number of traces 6886
number of attributes 11

In [9]:
MISSING_VALUE = "MISSING_VALUE"

In [10]:
if ACT_TIME_ONLY:
    categorical_columns = ["Activity"]
    real_value_columns = ["time:timestamp"]
    dataset = f"{dataset}_AT_only"
else:
    categorical_columns = dataset_info["categorical"]
    real_value_columns = dataset_info["numerical"]

In [11]:
list_unique = {k : list(tab_all[k].unique()) + [MISSING_VALUE] for k in categorical_columns}
#list_unique

In [12]:
import random

torch.manual_seed(0)
torch.cuda.manual_seed(0)
random.seed(0)
np.random.seed(0)

In [13]:
with open(data_dir_graphs + dataset + "_TRAIN_V2_repair.pkl", "rb") as f:
    X_train = pickle.load(f)
with open(data_dir_graphs + dataset + "_VALID_V2_repair.pkl", "rb") as f:
    X_valid = pickle.load(f)
with open(data_dir_graphs + dataset + "_TEST_V2_repair.pkl", "rb") as f:
    X_test = pickle.load(f)

In [14]:
from torch_geometric.loader import DataLoader
from torch_geometric.transforms import ToUndirected

transform = ToUndirected()


with torch.no_grad():
        for i in range(len(X_train)):
                X_train[i] = transform(X_train[i])
        for i in range(len(X_valid)):
                X_valid[i] = transform(X_valid[i])
        for i in range(len(X_test)):
                X_test[i] = transform(X_test[i])

In [15]:
edge_types = set()
node_types = set()
for i in range(len(X_train)):
    n, edge_type = X_train[i].metadata()
    for x in n:
        node_types.add(x)
    for x in edge_type:
        edge_types.add(x)
for i in range(len(X_valid)):
    n, edge_type = X_valid[i].metadata()
    for x in n:
        node_types.add(x)
    for x in edge_type:
        edge_types.add(x)
for i in range(len(X_test)):
    n, edge_type = X_test[i].metadata()
    for x in n:
        node_types.add(x)
    for x in edge_type:
        edge_types.add(x)
        
node_types = list(node_types)
edge_types = list(edge_types)

## Hyperopt

In [16]:
from ax.service.managed_loop import optimize
from torch_geometric.nn import (
    HeteroConv,
    SAGEConv
)
from torch.nn import (
    ModuleList,
    Module,
    Linear,
    ModuleDict
  )
from typing_extensions import Self

In [20]:
class HGNN(Module):

    def __init__(self, output_cat, output_real,nodes_relations, parameters) -> Self:  # type: ignore
        super().__init__()

        # List of convolutional layers
        
        hid = parameters["hid"]
        layers = parameters["layers"]
        aggregation = parameters["aggregation"]
       
        
        self.output_cat = output_cat
        self.output_real = output_real
        
        self.convs = ModuleList()
        for _ in range(layers):
            conv = HeteroConv(
                {
                    relation: (
                        #TransformerConv((-1,-1), hid)
                        SAGEConv((-1,-1), aggr=aggregation, out_channels=hid, normalize=False)
                        # GATv2Conv((-1,-1), add_self_loops=False, out_channels=hid, concat=False)
                    )
                    for relation in nodes_relations
                },
                aggr=aggregation,
            )

            self.convs.append(conv)

        self.FC = ModuleDict()
        
        for k in output_cat:
            self.FC[k] = Linear(hid, output_cat[k], device=device)
        for k in output_real:
            self.FC[k] = Linear(hid, 1, device=device)
        
    
        
        

    def forward(self, batch):

        for i in range(len(self.convs)):
            batch.x_dict = self.convs[i]( 
                batch.x_dict, batch.edge_index_dict
            )
            batch.x_dict = {key: x.relu() for key, x in batch.x_dict.items()}

        output = {}
        
        for k in self.output_cat:
            output[k] = self.FC[k](batch.x_dict[k][batch.masks[k]])
        for k in self.output_real:
            output[k] = self.FC[k](batch.x_dict[k][batch.masks[k]]).reshape(1,-1)[0]
            

        return output

In [21]:
from torcheval.metrics.functional import multiclass_accuracy, multiclass_f1_score
import torch.nn as nn
from copy import deepcopy
from tqdm.notebook import tqdm


def train_hgnn(config, output_cat, output_real, epochs=20):
    print(config)

    net = HGNN(
        parameters=config,
        output_cat=output_cat,
        output_real=output_real,
        nodes_relations=edge_types,
    )
    net = net.to(device)

    losses = {}

    for k in output_cat:
        losses[k] = nn.CrossEntropyLoss()
    for k in output_real:
        losses[k] = nn.L1Loss()

    train_loader = DataLoader(X_train, batch_size=config["batch_size"], shuffle=True)
    valid_loader = DataLoader(X_valid, batch_size=config["batch_size"], shuffle=True)

    optimizer = torch.optim.Adam(net.parameters(), lr=config["lr"], weight_decay=config["weight_decay"])

    best_model = None
    best_loss = 0
    patience = 5
    pat_count = 0

    torch.cuda.empty_cache()

    for epoch in tqdm(range(0, epochs)):

        net.train()
        for _, x in enumerate(train_loader):
            x = x.to(device)

            # TESTTTTTTTTTTT
            #x.mask = torch.full_like(x.mask, fill_value=True)
            #########################
            
            all_labels = x.y
            labels = {k: all_labels[k][x.masks[k]] for k in all_labels}

            optimizer.zero_grad()
            outputs = net(x)

            losses_step = {k: losses[k](outputs[k], labels[k]) for k in losses}

            total_loss = 0
            for k in losses_step:
                total_loss += losses_step[k]

            total_loss.backward()
            optimizer.step()

        running_total_loss = []

        net.eval()
        with torch.no_grad():
            for i, x in enumerate(valid_loader):
                x = x.to(device)

                all_labels = x.y
                labels = {k: all_labels[k][x.masks[k]] for k in all_labels}

                outputs = net(x)

                losses_step = {k: losses[k](outputs[k], labels[k]) for k in losses}

                running_total_loss.append(sum(list(losses_step.values())))

        val_loss = sum(running_total_loss) / len(running_total_loss)

        if epoch == 0:
            best_model = deepcopy(net)
            best_loss = val_loss
        else:
            if val_loss < best_loss:
                best_loss = val_loss
                best_model = deepcopy(net)
                pat_count = 0
            if pat_count == patience:
                return best_model
        pat_count += 1

    return best_model

In [22]:
from torch.nn.functional import l1_loss
 
def test_hgnn(net, output_cat, output_real, test_graphs=X_test):
    test_loader = DataLoader(test_graphs, batch_size=128, shuffle=False)
    
    losses = {}
    
    for k in output_cat:
        losses[k] = (
            nn.CrossEntropyLoss()
        )
    for k in output_real:
        losses[k] = nn.L1Loss()
    
    
    
    
    
    predictions_categorical = {k: [] for k in output_cat}
    target_categorical = {k: [] for k in output_cat}

    avg_MAE = {k : [] for k in output_real}
    prediction_numerical = {k: [] for k in output_real}
    target_numerical = {k: [] for k in output_real}
    
    total_loss = []
        
    net.eval()
    with torch.no_grad():
        for _, x in enumerate(test_loader):
            x = x.to(device)
            
            all_labels = x.y
            labels = {k : all_labels[k][x.masks[k]] for k in all_labels}
            
            outputs = net(x)
            
     
            losses_step = {k: losses[k](outputs[k], labels[k]).item() for k in losses}
            total_loss.append(sum(list(losses_step.values())))
            
            for k in output_cat:
                predictions_categorical[k].append(
                        torch.argmax(torch.softmax(outputs[k], dim=1), 1)
                )
                target_categorical[k].append(labels[k])
            
            
            for k in output_real:
                prediction_numerical[k].append(
                    outputs[k]
                )
                target_numerical[k].append(
                    labels[k]
                )
                avg_MAE[k].append(losses_step[k])
                    
    for k in predictions_categorical:
            predictions_categorical[k] = torch.cat(predictions_categorical[k])
            target_categorical[k] = torch.cat(target_categorical[k])
               
    for k in prediction_numerical:
        prediction_numerical[k] = torch.cat(prediction_numerical[k])
        target_numerical[k] = torch.cat(target_numerical[k])
   
    
    MAE = {
        k: l1_loss(prediction_numerical[k], target_numerical[k]).item()
        for k in output_real
    }
    
    accuracy = {
            k: multiclass_accuracy(
                predictions_categorical[k],
                target_categorical[k],
                num_classes=output_cat[k],
            )
            for k in output_cat
        }
    
    avg_MAE = {k : sum(avg_MAE[k]) / len(avg_MAE[k]) for k in avg_MAE}
    
    
    Average_total_loss = sum(total_loss) / len(total_loss)
    
    res = {f"{k}_acc" : accuracy[k].item() for k in accuracy} | {f"{k}_mae" : avg_MAE[k] for k in avg_MAE} | {"AVG_total_loss" : Average_total_loss}  | {f"MAE_{k}" : MAE[k] for k in MAE}
    
    print(res)
    
    return res

In [23]:

outputcat = {k : len(list_unique[k]) for k in list_unique}
outputreal = real_value_columns

if ACT_TIME_ONLY:
    outputcat= {"Activity" : outputcat["Activity"]}
    outputreal = ['time:timestamp']

print(outputcat)
print(outputreal)

{'org:resource': 3, 'Activity': 20, 'org:role': 9, 'case:Project': 80, 'case:Task': 598, 'case:OrganizationalEntity': 37, 'case:Activity': 7, 'case:RfpNumber': 6323}
['time:timestamp', 'case:RequestedAmount']

In [24]:
def train_evaluate(config):
    trained_net = train_hgnn(config, output_cat=outputcat, output_real=outputreal, epochs=100)
    return test_hgnn(trained_net, output_cat=outputcat, output_real=outputreal)

In [25]:
import logging

logging.getLogger("root").setLevel(logging.ERROR)

import warnings
warnings.filterwarnings("ignore", category=UserWarning)

In [ ]:
#outputreal = ['time:timestamp']
#outputcat = {"Activity" : outputcat["Activity"]}
#print(outputcat)

In [27]:
best_parameters, values, experiment, model = optimize(
    parameters=[
        {"name": "hid", "type": "choice", "values": [128], "value_type": "int", "is_ordered" : True,"sort_values":False},
        #{"name": "layers", "type": "choice", "values": [2, 3, 4, 5], "value_type": "int", "is_ordered" : True, "sort_values":False},
        {"name": "layers", "type": "choice", "values": [2,4], "value_type": "int", "is_ordered" : True, "sort_values":False},
        {"name": "lr", "type": "range", "bounds": [1e-4, 1e-2], "value_type": "float", "log_scale": True},
        {"name": "batch_size", "type": "choice", "values": [128,256,512], "value_type": "int", "is_ordered" : True,"sort_values":False},
        #{"name": "batch_size", "type": "choice", "values": [32, 64, 512], "value_type": "int", "is_ordered" : True,"sort_values":False}, 
        {"name": "weight_decay", "type": "range", "bounds" : [1e-2, 1e-1], "value_type": "float", "log_scale" : True}, 
        #{"name": "heads", "type": "choice", "values": [1,2], "value_type": "int", "is_ordered" : True,"sort_values":False},
        #{"name": "heads", "type": "choice", "values": [1], "value_type": "int", "is_ordered" : True,"sort_values":False},
        
        #{"name": "aggregation", "type" : "choice", "values" :["sum", "mean", "max"], "value_type" : "str"}
        {"name": "aggregation", "type" : "choice", "values" :["max","sum"], "value_type" : "str"},
     
    ],
  
    evaluation_function=train_evaluate,
    objective_name='AVG_total_loss',
    arms_per_trial=1,
    minimize = True,
    random_seed = 123,
    total_trials = 50
)

print(best_parameters)
means, covariances = values
print(means)
print(experiment)

[INFO 11-12 10:59:32] ax.service.utils.instantiation: Choice parameter hid contains only one value, converting to a fixed parameter instead.
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/ax/service/utils/instantiation.py:248: AxParameterWarning: `is_ordered` is not specified for `ChoiceParameter` "aggregation". Defaulting to `True`  since there are exactly two choices.. To override this behavior (or avoid this warning), specify `is_ordered` during `ChoiceParameter` construction. Note that choice parameters with exactly 2 choices are always considered ordered and that the user-supplied `is_ordered` has no effect in this particular case.
  return ChoiceParameter(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/ax/service/utils/instantiation.py:248: AxParameterWarning: `sort_values` is not specified for `ChoiceParameter` "aggregation". Defaulting to `False` for parameters of `ParameterType` STRING. To override this behavior (or avoid this warning), specify `sort_values` during `ChoiceParameter` construction.
  return ChoiceParameter(
[INFO 11-12 10:59:32] ax.service.utils.instantiation: Created search space: SearchSpace(parameters=[FixedParameter(name='hid', parameter_type=INT, value=128), ChoiceParameter(name='layers', parameter_type=INT, values=[2, 4], is_ordered=True, sort_values=False), RangeParameter(name='lr', parameter_type=FLOAT, range=[0.0001, 0.01], log_scale=True), ChoiceParameter(name='batch_size', parameter_type=INT, values=[128, 256, 512], is_ordered=True, sort_values=False), RangeParameter(name='weight_decay', parameter_type=FLOAT, range=[0.01, 0.1], log_scale=True), ChoiceParameter(name='aggregation', parameter_type=STRING, values=['max', 'sum'], is_ordered=True, sort_values=False)], parameter_constraints=[]).
[INFO 11-12 10:59:32] ax.modelbridge.dispatch_utils: Using Models.BOTORCH_MODULAR since there is at least one ordered parameter and there are no unordered categorical parameters.
[INFO 11-12 10:59:32] ax.modelbridge.dispatch_utils: Calculating the number of remaining initialization trials based on num_initialization_trials=None max_initialization_trials=None num_tunable_parameters=5 num_trials=None use_batch_trials=False
[INFO 11-12 10:59:32] ax.modelbridge.dispatch_utils: calculated num_initialization_trials=10
[INFO 11-12 10:59:32] ax.modelbridge.dispatch_utils: num_completed_initialization_trials=0 num_remaining_initialization_trials=10
[INFO 11-12 10:59:32] ax.modelbridge.dispatch_utils: `verbose`, `disable_progbar`, and `jit_compile` are not yet supported when using `choose_generation_strategy` with ModularBoTorchModel, dropping these arguments.
[INFO 11-12 10:59:32] ax.modelbridge.dispatch_utils: Using Bayesian Optimization generation strategy: GenerationStrategy(name='Sobol+BoTorch', steps=[Sobol for 10 trials, BoTorch for subsequent trials]). Iterations after 10 will take longer to generate due to model-fitting.
[INFO 11-12 10:59:32] ax.service.managed_loop: Started full optimization with 50 steps.
[INFO 11-12 10:59:32] ax.service.managed_loop: Running optimization trial 1...

{'layers': 2, 'lr': 0.0014528509914685322, 'batch_size': 256, 'weight_decay': 0.09787123410578823, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 11:04:42] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 11:04:42] ax.service.managed_loop: Running optimization trial 2...
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:04:42] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None

{'org:resource_acc': 0.931147038936615, 'Activity_acc': 0.8233917951583862, 'org:role_acc': 0.8227332830429077, 'case:Project_acc': 0.2770439088344574, 'case:Task_acc': 0.7536268830299377, 'case:OrganizationalEntity_acc': 0.22061970829963684, 'case:Activity_acc': 0.9820506572723389, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006602124336899983, 'case:RequestedAmount_mae': 0.25238548081230233, 'AVG_total_loss': 17.532494372507145, 'MAE_time:timestamp': 0.006709863431751728, 'MAE_case:RequestedAmount': 0.2524721920490265}
{'layers': 4, 'lr': 0.00029413132884013236, 'batch_size': 512, 'weight_decay': 0.020455714056727532, 'aggregation': 'max', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 11:10:37] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 11:10:37] ax.service.managed_loop: Running optimization trial 3...
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:10:37] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None

{'org:resource_acc': 0.9749579429626465, 'Activity_acc': 0.8738875985145569, 'org:role_acc': 0.9410807490348816, 'case:Project_acc': 0.1593308448791504, 'case:Task_acc': 0.7554147839546204, 'case:OrganizationalEntity_acc': 0.6039649248123169, 'case:Activity_acc': 0.9927895665168762, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.045387448467038294, 'case:RequestedAmount_mae': 0.07974016466350467, 'AVG_total_loss': 17.605424944419173, 'MAE_time:timestamp': 0.04526049271225929, 'MAE_case:RequestedAmount': 0.080362968146801}
{'layers': 4, 'lr': 0.0048542703684471035, 'batch_size': 128, 'weight_decay': 0.045971850882169055, 'aggregation': 'max', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 11:12:54] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 11:12:54] ax.service.managed_loop: Running optimization trial 4...
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:12:54] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None

{'org:resource_acc': 0.9666445851325989, 'Activity_acc': 0.8339180946350098, 'org:role_acc': 0.8178997039794922, 'case:Project_acc': 0.0990462601184845, 'case:Task_acc': 0.7536268830299377, 'case:OrganizationalEntity_acc': 0.08510854840278625, 'case:Activity_acc': 0.9843518137931824, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00765864579524431, 'case:RequestedAmount_mae': 0.17256813496351242, 'AVG_total_loss': 17.87151861745278, 'MAE_time:timestamp': 0.007761929649859667, 'MAE_case:RequestedAmount': 0.17316336929798126}
{'layers': 2, 'lr': 0.0008802227321016593, 'batch_size': 256, 'weight_decay': 0.01281482433257483, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 11:17:10] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 11:17:10] ax.service.managed_loop: Running optimization trial 5...
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:17:10] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None

{'org:resource_acc': 0.9614423513412476, 'Activity_acc': 0.922400176525116, 'org:role_acc': 0.9413859844207764, 'case:Project_acc': 0.8521446585655212, 'case:Task_acc': 0.7558234930038452, 'case:OrganizationalEntity_acc': 0.8689226508140564, 'case:Activity_acc': 0.9870621562004089, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00618149518656234, 'case:RequestedAmount_mae': 0.14752179480813168, 'AVG_total_loss': 13.851181183208677, 'MAE_time:timestamp': 0.006264821160584688, 'MAE_case:RequestedAmount': 0.14850082993507385}
{'layers': 2, 'lr': 0.006798744489941672, 'batch_size': 512, 'weight_decay': 0.014659497468558654, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 11:20:38] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 11:20:38] ax.service.managed_loop: Running optimization trial 6...
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:20:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.961646318435669, 'Activity_acc': 0.9147215485572815, 'org:role_acc': 0.9388419985771179, 'case:Project_acc': 0.842454195022583, 'case:Task_acc': 0.7555169463157654, 'case:OrganizationalEntity_acc': 0.8731525540351868, 'case:Activity_acc': 0.9660956263542175, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006717940594104153, 'case:RequestedAmount_mae': 0.23282057019295516, 'AVG_total_loss': 13.398103627764309, 'MAE_time:timestamp': 0.006826924625784159, 'MAE_case:RequestedAmount': 0.2328735738992691}
{'layers': 4, 'lr': 0.00035047997672635827, 'batch_size': 256, 'weight_decay': 0.039436578351773444, 'aggregation': 'max', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 11:24:00] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 11:24:00] ax.service.managed_loop: Running optimization trial 7...
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:24:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9728158116340637, 'Activity_acc': 0.8194253444671631, 'org:role_acc': 0.9109596014022827, 'case:Project_acc': 0.14051103591918945, 'case:Task_acc': 0.7532693147659302, 'case:OrganizationalEntity_acc': 0.12975232303142548, 'case:Activity_acc': 0.9908974766731262, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.033108846491409674, 'case:RequestedAmount_mae': 0.08309763421614964, 'AVG_total_loss': 18.7167974109244, 'MAE_time:timestamp': 0.03320447355508804, 'MAE_case:RequestedAmount': 0.08387022465467453}
{'layers': 4, 'lr': 0.0021138872518101184, 'batch_size': 512, 'weight_decay': 0.031203678344553825, 'aggregation': 'max', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 11:27:06] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 11:27:06] ax.service.managed_loop: Running optimization trial 8...
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:27:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9774570465087891, 'Activity_acc': 0.8771421313285828, 'org:role_acc': 0.9292765259742737, 'case:Project_acc': 0.13495180010795593, 'case:Task_acc': 0.7519411444664001, 'case:OrganizationalEntity_acc': 0.11064111441373825, 'case:Activity_acc': 0.9934031963348389, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.037877443005089405, 'case:RequestedAmount_mae': 0.1635888220259437, 'AVG_total_loss': 18.23377475828898, 'MAE_time:timestamp': 0.03770488500595093, 'MAE_case:RequestedAmount': 0.1643446981906891}
{'layers': 2, 'lr': 0.00011271059564696324, 'batch_size': 128, 'weight_decay': 0.06295743798248213, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 11:51:46] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 11:51:46] ax.service.managed_loop: Running optimization trial 9...
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:51:46] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9315040707588196, 'Activity_acc': 0.871192455291748, 'org:role_acc': 0.8874020576477051, 'case:Project_acc': 0.4160758852958679, 'case:Task_acc': 0.7536268830299377, 'case:OrganizationalEntity_acc': 0.6787789463996887, 'case:Activity_acc': 0.9870621562004089, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006594471435097081, 'case:RequestedAmount_mae': 0.1552289906475279, 'AVG_total_loss': 16.11148029511484, 'MAE_time:timestamp': 0.006706276908516884, 'MAE_case:RequestedAmount': 0.15570451319217682}
{'layers': 2, 'lr': 0.003285171097957902, 'batch_size': 256, 'weight_decay': 0.03300587986238524, 'aggregation': 'max', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 11:58:10] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 11:58:10] ax.service.managed_loop: Running optimization trial 10...
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 11:58:10] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.932218074798584, 'Activity_acc': 0.823239266872406, 'org:role_acc': 0.9054645895957947, 'case:Project_acc': 0.5800479650497437, 'case:Task_acc': 0.7536268830299377, 'case:OrganizationalEntity_acc': 0.7742329835891724, 'case:Activity_acc': 0.9799028635025024, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006616339397927125, 'case:RequestedAmount_mae': 0.10080058569157566, 'AVG_total_loss': 15.02967195528456, 'MAE_time:timestamp': 0.0067214989103376865, 'MAE_case:RequestedAmount': 0.10160607099533081}
{'layers': 4, 'lr': 0.0007123006581692218, 'batch_size': 128, 'weight_decay': 0.016368037085418573, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:00:21] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:00:21] ax.service.managed_loop: Running optimization trial 11...
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:00:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9774570465087891, 'Activity_acc': 0.9209763407707214, 'org:role_acc': 0.9548183679580688, 'case:Project_acc': 0.8825929164886475, 'case:Task_acc': 0.7551082968711853, 'case:OrganizationalEntity_acc': 0.8888492584228516, 'case:Activity_acc': 0.9806699156761169, 'case:RfpNumber_acc': 0.0393945686519146, 'time:timestamp_mae': 0.016703530145740067, 'case:RequestedAmount_mae': 0.161215808932428, 'AVG_total_loss': 13.027218980730847, 'MAE_time:timestamp': 0.01681297831237316, 'MAE_case:RequestedAmount': 0.16199243068695068}
{'layers': 4, 'lr': 0.01, 'batch_size': 512, 'weight_decay': 0.01745648967147293, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:04:16] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:04:16] ax.service.managed_loop: Running optimization trial 12...
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:04:16] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9842913150787354, 'Activity_acc': 0.9231629371643066, 'org:role_acc': 0.9658085107803345, 'case:Project_acc': 0.8912123441696167, 'case:Task_acc': 0.7555169463157654, 'case:OrganizationalEntity_acc': 0.8742228150367737, 'case:Activity_acc': 0.9933009743690491, 'case:RfpNumber_acc': 0.0392908975481987, 'time:timestamp_mae': 0.006698489012369128, 'case:RequestedAmount_mae': 0.1879373944743916, 'AVG_total_loss': 13.105389431244005, 'MAE_time:timestamp': 0.0068044415675103664, 'MAE_case:RequestedAmount': 0.18898187577724457}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.01950806160644494, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:09:47] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:09:47] ax.service.managed_loop: Running optimization trial 13...
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:09:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9748049378395081, 'Activity_acc': 0.9471141695976257, 'org:role_acc': 0.9565483331680298, 'case:Project_acc': 0.904931902885437, 'case:Task_acc': 0.7536268830299377, 'case:OrganizationalEntity_acc': 0.9122923016548157, 'case:Activity_acc': 0.9937611818313599, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00635294367869695, 'case:RequestedAmount_mae': 0.13811586024584593, 'AVG_total_loss': 11.926921283757245, 'MAE_time:timestamp': 0.006471921689808369, 'MAE_case:RequestedAmount': 0.13918565213680267}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.02395503544270839, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:12:43] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:12:43] ax.service.managed_loop: Running optimization trial 14...
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:12:43] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9825572371482849, 'Activity_acc': 0.9123823642730713, 'org:role_acc': 0.9568027257919312, 'case:Project_acc': 0.8284796476364136, 'case:Task_acc': 0.7558745741844177, 'case:OrganizationalEntity_acc': 0.8770257830619812, 'case:Activity_acc': 0.9915622472763062, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.013389962345913605, 'case:RequestedAmount_mae': 0.2111224087852019, 'AVG_total_loss': 12.352106991064458, 'MAE_time:timestamp': 0.013441326096653938, 'MAE_case:RequestedAmount': 0.21205760538578033}
{'layers': 2, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.019861234645174683, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:16:03] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:16:03] ax.service.managed_loop: Running optimization trial 15...
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:16:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9657264947891235, 'Activity_acc': 0.8661072850227356, 'org:role_acc': 0.9370611906051636, 'case:Project_acc': 0.7916050553321838, 'case:Task_acc': 0.7559767365455627, 'case:OrganizationalEntity_acc': 0.848333477973938, 'case:Activity_acc': 0.9646637439727783, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006292099926482748, 'case:RequestedAmount_mae': 0.19738872501033325, 'AVG_total_loss': 13.239177486376354, 'MAE_time:timestamp': 0.006404339801520109, 'MAE_case:RequestedAmount': 0.1984979510307312}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:18:38] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:18:38] ax.service.managed_loop: Running optimization trial 16...
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:18:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9781200289726257, 'Activity_acc': 0.9230612516403198, 'org:role_acc': 0.9631627202033997, 'case:Project_acc': 0.8375070095062256, 'case:Task_acc': 0.7545974850654602, 'case:OrganizationalEntity_acc': 0.9073998332023621, 'case:Activity_acc': 0.9952442049980164, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00792044664181217, 'case:RequestedAmount_mae': 0.18650226488157554, 'AVG_total_loss': 12.15511003717849, 'MAE_time:timestamp': 0.008015337400138378, 'MAE_case:RequestedAmount': 0.18684504926204681}
{'layers': 2, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.01, 'aggregation': 'max', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:22:07] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:22:07] ax.service.managed_loop: Running optimization trial 17...
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:22:07] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.954710066318512, 'Activity_acc': 0.9108568429946899, 'org:role_acc': 0.9261727929115295, 'case:Project_acc': 0.8330188393592834, 'case:Task_acc': 0.7540355920791626, 'case:OrganizationalEntity_acc': 0.8795739412307739, 'case:Activity_acc': 0.9870621562004089, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00650447199155611, 'case:RequestedAmount_mae': 0.17447497916442375, 'AVG_total_loss': 12.74302182453512, 'MAE_time:timestamp': 0.0066278292797505856, 'MAE_case:RequestedAmount': 0.17573745548725128}
{'layers': 2, 'lr': 0.01, 'batch_size': 512, 'weight_decay': 0.01, 'aggregation': 'max', 'hid': 128}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:26:21] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:26:21] ax.service.managed_loop: Running optimization trial 18...
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:26:21] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9564441442489624, 'Activity_acc': 0.9029239416122437, 'org:role_acc': 0.923832356929779, 'case:Project_acc': 0.8573978543281555, 'case:Task_acc': 0.7537801265716553, 'case:OrganizationalEntity_acc': 0.8697890043258667, 'case:Activity_acc': 0.9870621562004089, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006326003340762798, 'case:RequestedAmount_mae': 0.12879620699418914, 'AVG_total_loss': 13.302193869030345, 'MAE_time:timestamp': 0.006444403901696205, 'MAE_case:RequestedAmount': 0.12960690259933472}
{'layers': 2, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.01, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:30:57] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:30:57] ax.service.managed_loop: Running optimization trial 19...
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:30:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9659815430641174, 'Activity_acc': 0.924434244632721, 'org:role_acc': 0.9431667923927307, 'case:Project_acc': 0.8766257166862488, 'case:Task_acc': 0.7546996474266052, 'case:OrganizationalEntity_acc': 0.8868107199668884, 'case:Activity_acc': 0.9852722883224487, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006712638660920439, 'case:RequestedAmount_mae': 0.12808984338685317, 'AVG_total_loss': 12.577825082284916, 'MAE_time:timestamp': 0.0068422951735556126, 'MAE_case:RequestedAmount': 0.12932981550693512}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.01857918938123213, 'aggregation': 'sum', 'hid': 128}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:35:30] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:35:30] ax.service.managed_loop: Running optimization trial 20...
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:35:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.976947009563446, 'Activity_acc': 0.9345537424087524, 'org:role_acc': 0.9591940641403198, 'case:Project_acc': 0.8893252611160278, 'case:Task_acc': 0.7546996474266052, 'case:OrganizationalEntity_acc': 0.9041891694068909, 'case:Activity_acc': 0.9926872849464417, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.007363553762573887, 'case:RequestedAmount_mae': 0.1347071067602546, 'AVG_total_loss': 12.243738507425102, 'MAE_time:timestamp': 0.007479922380298376, 'MAE_case:RequestedAmount': 0.13589008152484894}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.019862038779240688, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:39:47] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:39:47] ax.service.managed_loop: Running optimization trial 21...
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:39:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9804661273956299, 'Activity_acc': 0.9261123538017273, 'org:role_acc': 0.9577694535255432, 'case:Project_acc': 0.8991686701774597, 'case:Task_acc': 0.7554658651351929, 'case:OrganizationalEntity_acc': 0.8708083033561707, 'case:Activity_acc': 0.9928918480873108, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.007163297928248842, 'case:RequestedAmount_mae': 0.19421973410579893, 'AVG_total_loss': 11.990136916531439, 'MAE_time:timestamp': 0.007245007436722517, 'MAE_case:RequestedAmount': 0.19560937583446503}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.01, 'aggregation': 'max', 'hid': 128}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 12:42:14] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 12:42:14] ax.service.managed_loop: Running optimization trial 22...
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 12:42:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9779670238494873, 'Activity_acc': 0.9222476482391357, 'org:role_acc': 0.9526814222335815, 'case:Project_acc': 0.8762686848640442, 'case:Task_acc': 0.7596036195755005, 'case:OrganizationalEntity_acc': 0.8670879602432251, 'case:Activity_acc': 0.9947327971458435, 'case:RfpNumber_acc': 0.03882438316941261, 'time:timestamp_mae': 0.006018778960289502, 'case:RequestedAmount_mae': 0.12100781417555279, 'AVG_total_loss': 12.733660527662357, 'MAE_time:timestamp': 0.006123834289610386, 'MAE_case:RequestedAmount': 0.12170059233903885}
{'layers': 2, 'lr': 0.0001, 'batch_size': 128, 'weight_decay': 0.015268842931810977, 'aggregation': 'max', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:08:48] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:08:48] ax.service.managed_loop: Running optimization trial 23...
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:08:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9586881995201111, 'Activity_acc': 0.9017543792724609, 'org:role_acc': 0.9208812713623047, 'case:Project_acc': 0.7685010433197021, 'case:Task_acc': 0.7537801265716553, 'case:OrganizationalEntity_acc': 0.8357965350151062, 'case:Activity_acc': 0.9870621562004089, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006462502586482851, 'case:RequestedAmount_mae': 0.07467931922939089, 'AVG_total_loss': 14.30257710221189, 'MAE_time:timestamp': 0.006584511138498783, 'MAE_case:RequestedAmount': 0.07555005699396133}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 2, 'lr': 0.0001, 'batch_size': 128, 'weight_decay': 0.1, 'aggregation': 'max', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:22:57] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:22:57] ax.service.managed_loop: Running optimization trial 24...
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:22:57] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.8865200877189636, 'Activity_acc': 0.45746248960494995, 'org:role_acc': 0.6899867653846741, 'case:Project_acc': 0.09899525344371796, 'case:Task_acc': 0.7536268830299377, 'case:OrganizationalEntity_acc': 0.11145652830600739, 'case:Activity_acc': 0.9788801074028015, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00770363309075711, 'case:RequestedAmount_mae': 0.13226974472679473, 'AVG_total_loss': 19.72498236673332, 'MAE_time:timestamp': 0.007773567456752062, 'MAE_case:RequestedAmount': 0.13312757015228271}
{'layers': 2, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.018376242930857267, 'aggregation': 'max', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:29:05] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:29:05] ax.service.managed_loop: Running optimization trial 25...
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:29:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9534859657287598, 'Activity_acc': 0.8911263346672058, 'org:role_acc': 0.9092805981636047, 'case:Project_acc': 0.7545264363288879, 'case:Task_acc': 0.7536268830299377, 'case:OrganizationalEntity_acc': 0.8264703154563904, 'case:Activity_acc': 0.9870621562004089, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.007844553924062185, 'case:RequestedAmount_mae': 0.1086717699136999, 'AVG_total_loss': 13.5541166963004, 'MAE_time:timestamp': 0.007952769286930561, 'MAE_case:RequestedAmount': 0.10936281830072403}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.023782162819977328, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:33:05] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:33:05] ax.service.managed_loop: Running optimization trial 26...
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:33:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9763349890708923, 'Activity_acc': 0.9412153363227844, 'org:role_acc': 0.9540551900863647, 'case:Project_acc': 0.8854490518569946, 'case:Task_acc': 0.7538822889328003, 'case:OrganizationalEntity_acc': 0.8830394744873047, 'case:Activity_acc': 0.9947327971458435, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006535633652539992, 'case:RequestedAmount_mae': 0.1772225132143056, 'AVG_total_loss': 12.090822005752232, 'MAE_time:timestamp': 0.006647443398833275, 'MAE_case:RequestedAmount': 0.17835114896297455}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.027119949012781495, 'aggregation': 'sum', 'hid': 128}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:36:48] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:36:48] ax.service.managed_loop: Running optimization trial 27...
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:36:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9768959879875183, 'Activity_acc': 0.9135519862174988, 'org:role_acc': 0.9524270296096802, 'case:Project_acc': 0.812515914440155, 'case:Task_acc': 0.7568961977958679, 'case:OrganizationalEntity_acc': 0.8668841123580933, 'case:Activity_acc': 0.990181565284729, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006133616867440718, 'case:RequestedAmount_mae': 0.18627929659905257, 'AVG_total_loss': 12.346446162436795, 'MAE_time:timestamp': 0.0062491921707987785, 'MAE_case:RequestedAmount': 0.186848446726799}
{'layers': 2, 'lr': 0.01, 'batch_size': 512, 'weight_decay': 0.01, 'aggregation': 'sum', 'hid': 128}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:39:55] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:39:55] ax.service.managed_loop: Running optimization trial 28...
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:39:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9627683758735657, 'Activity_acc': 0.9121789932250977, 'org:role_acc': 0.9422000646591187, 'case:Project_acc': 0.8595399260520935, 'case:Task_acc': 0.7543931603431702, 'case:OrganizationalEntity_acc': 0.882886528968811, 'case:Activity_acc': 0.9870621562004089, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.007167533678175123, 'case:RequestedAmount_mae': 0.15439043649368817, 'AVG_total_loss': 12.984204613888222, 'MAE_time:timestamp': 0.007280176505446434, 'MAE_case:RequestedAmount': 0.15450003743171692}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.026780532311999103, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:42:47] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:42:47] ax.service.managed_loop: Running optimization trial 29...
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:42:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9767429828643799, 'Activity_acc': 0.924586832523346, 'org:role_acc': 0.8985957503318787, 'case:Project_acc': 0.8285816311836243, 'case:Task_acc': 0.7554658651351929, 'case:OrganizationalEntity_acc': 0.8619916439056396, 'case:Activity_acc': 0.9881360530853271, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00674583278251467, 'case:RequestedAmount_mae': 0.2624689257807202, 'AVG_total_loss': 12.73169084462818, 'MAE_time:timestamp': 0.006863380782306194, 'MAE_case:RequestedAmount': 0.2634965777397156}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.023239295556673586, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:47:37] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:47:37] ax.service.managed_loop: Running optimization trial 30...
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:47:37] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9729688167572021, 'Activity_acc': 0.9408593773841858, 'org:role_acc': 0.9509006142616272, 'case:Project_acc': 0.8919773697853088, 'case:Task_acc': 0.7561299800872803, 'case:OrganizationalEntity_acc': 0.9077566266059875, 'case:Activity_acc': 0.9925850033760071, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.007548788355456458, 'case:RequestedAmount_mae': 0.18113561374721704, 'AVG_total_loss': 12.004965085415515, 'MAE_time:timestamp': 0.007644995581358671, 'MAE_case:RequestedAmount': 0.18243177235126495}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.02377086935626392, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:53:22] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:53:22] ax.service.managed_loop: Running optimization trial 31...
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:53:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9703167080879211, 'Activity_acc': 0.9442664384841919, 'org:role_acc': 0.9525287747383118, 'case:Project_acc': 0.8437292575836182, 'case:Task_acc': 0.7563853859901428, 'case:OrganizationalEntity_acc': 0.873764157295227, 'case:Activity_acc': 0.9928918480873108, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.009090136822864966, 'case:RequestedAmount_mae': 0.17470629596047932, 'AVG_total_loss': 12.113622716205471, 'MAE_time:timestamp': 0.009156877174973488, 'MAE_case:RequestedAmount': 0.17590764164924622}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.02403033126517537, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 13:57:55] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 13:57:55] ax.service.managed_loop: Running optimization trial 32...
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 13:57:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9762329459190369, 'Activity_acc': 0.9477751851081848, 'org:role_acc': 0.9568535685539246, 'case:Project_acc': 0.9049829244613647, 'case:Task_acc': 0.7541377544403076, 'case:OrganizationalEntity_acc': 0.8978188037872314, 'case:Activity_acc': 0.9926361441612244, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006048322094742347, 'case:RequestedAmount_mae': 0.17463263234606496, 'AVG_total_loss': 12.027759080463849, 'MAE_time:timestamp': 0.006162003148347139, 'MAE_case:RequestedAmount': 0.17588680982589722}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.024223640304303455, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:02:45] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:02:45] ax.service.managed_loop: Running optimization trial 33...
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:02:45] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.970112681388855, 'Activity_acc': 0.923366367816925, 'org:role_acc': 0.9471863508224487, 'case:Project_acc': 0.8513286113739014, 'case:Task_acc': 0.7561299800872803, 'case:OrganizationalEntity_acc': 0.9143818020820618, 'case:Activity_acc': 0.9874712228775024, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00681376784901928, 'case:RequestedAmount_mae': 0.13608969761817544, 'AVG_total_loss': 12.247318558300051, 'MAE_time:timestamp': 0.006916755344718695, 'MAE_case:RequestedAmount': 0.13712947070598602}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.02407107116761824, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:09:00] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:09:00] ax.service.managed_loop: Running optimization trial 34...
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:09:00] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9751109480857849, 'Activity_acc': 0.9337909817695618, 'org:role_acc': 0.95257967710495, 'case:Project_acc': 0.8777477145195007, 'case:Task_acc': 0.7556702494621277, 'case:OrganizationalEntity_acc': 0.9176944494247437, 'case:Activity_acc': 0.993607759475708, 'case:RfpNumber_acc': 0.03892805427312851, 'time:timestamp_mae': 0.008970723746137487, 'case:RequestedAmount_mae': 0.19023607036581747, 'AVG_total_loss': 12.22990473538219, 'MAE_time:timestamp': 0.00906219519674778, 'MAE_case:RequestedAmount': 0.19141407310962677}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.02293529412697132, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:12:14] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:12:14] ax.service.managed_loop: Running optimization trial 35...
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:12:14] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9678686261177063, 'Activity_acc': 0.9296720027923584, 'org:role_acc': 0.953698992729187, 'case:Project_acc': 0.8400571346282959, 'case:Task_acc': 0.7561299800872803, 'case:OrganizationalEntity_acc': 0.914076030254364, 'case:Activity_acc': 0.9756584167480469, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006153499936098578, 'case:RequestedAmount_mae': 0.14643284443903853, 'AVG_total_loss': 12.24902020410863, 'MAE_time:timestamp': 0.006268313620239496, 'MAE_case:RequestedAmount': 0.14765788614749908}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.022974608425951806, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:19:05] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:19:05] ax.service.managed_loop: Running optimization trial 36...
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:19:05] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9802111387252808, 'Activity_acc': 0.9447240829467773, 'org:role_acc': 0.9578202962875366, 'case:Project_acc': 0.9015147686004639, 'case:Task_acc': 0.7544442415237427, 'case:OrganizationalEntity_acc': 0.9160636067390442, 'case:Activity_acc': 0.9926872849464417, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006341395050252753, 'case:RequestedAmount_mae': 0.12432933916096334, 'AVG_total_loss': 11.839662332268846, 'MAE_time:timestamp': 0.006457926705479622, 'MAE_case:RequestedAmount': 0.12537719309329987}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.02280028488591261, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:27:38] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:27:38] ax.service.managed_loop: Running optimization trial 37...
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:27:38] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9782220721244812, 'Activity_acc': 0.9399948716163635, 'org:role_acc': 0.9560394883155823, 'case:Project_acc': 0.8910593390464783, 'case:Task_acc': 0.7542399168014526, 'case:OrganizationalEntity_acc': 0.8722862005233765, 'case:Activity_acc': 0.9929429888725281, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006335591379967, 'case:RequestedAmount_mae': 0.14335039368382207, 'AVG_total_loss': 11.992832563748514, 'MAE_time:timestamp': 0.006454023066908121, 'MAE_case:RequestedAmount': 0.14446473121643066}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.022542680198031993, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:31:30] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:31:30] ax.service.managed_loop: Running optimization trial 38...
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:31:30] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9773040413856506, 'Activity_acc': 0.943757951259613, 'org:role_acc': 0.9551236629486084, 'case:Project_acc': 0.891671359539032, 'case:Task_acc': 0.7570494413375854, 'case:OrganizationalEntity_acc': 0.8778411746025085, 'case:Activity_acc': 0.9899258613586426, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.007483879431944202, 'case:RequestedAmount_mae': 0.18008577437312515, 'AVG_total_loss': 12.099461431425341, 'MAE_time:timestamp': 0.007587299216538668, 'MAE_case:RequestedAmount': 0.18093910813331604}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.023387595973701797, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:33:55] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:33:55] ax.service.managed_loop: Running optimization trial 39...
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:33:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9798541069030762, 'Activity_acc': 0.9131451845169067, 'org:role_acc': 0.9541060924530029, 'case:Project_acc': 0.8429132103919983, 'case:Task_acc': 0.7541888356208801, 'case:OrganizationalEntity_acc': 0.8569462895393372, 'case:Activity_acc': 0.9926872849464417, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.007921746388698617, 'case:RequestedAmount_mae': 0.20532336361982204, 'AVG_total_loss': 12.497724963740135, 'MAE_time:timestamp': 0.008014926686882973, 'MAE_case:RequestedAmount': 0.20701327919960022}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.022621349978375112, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:37:47] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:37:47] ax.service.managed_loop: Running optimization trial 40...
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:37:47] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9729178547859192, 'Activity_acc': 0.9317569136619568, 'org:role_acc': 0.9517146944999695, 'case:Project_acc': 0.8912123441696167, 'case:Task_acc': 0.7576113939285278, 'case:OrganizationalEntity_acc': 0.8683111071586609, 'case:Activity_acc': 0.9929941296577454, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006248139832341285, 'case:RequestedAmount_mae': 0.2717276985446612, 'AVG_total_loss': 12.332022207817149, 'MAE_time:timestamp': 0.006357228383421898, 'MAE_case:RequestedAmount': 0.2731589078903198}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.022393284322992982, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:43:03] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:43:03] ax.service.managed_loop: Running optimization trial 41...
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:43:03] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9766409993171692, 'Activity_acc': 0.938011646270752, 'org:role_acc': 0.9658085107803345, 'case:Project_acc': 0.88136887550354, 'case:Task_acc': 0.7544442415237427, 'case:OrganizationalEntity_acc': 0.9090306758880615, 'case:Activity_acc': 0.9870621562004089, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00673599234195771, 'case:RequestedAmount_mae': 0.1562136626905865, 'AVG_total_loss': 11.878641474131857, 'MAE_time:timestamp': 0.006835023872554302, 'MAE_case:RequestedAmount': 0.15687038004398346}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.02241592437566286, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:48:28] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:48:28] ax.service.managed_loop: Running optimization trial 42...
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:48:28] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9730198383331299, 'Activity_acc': 0.9370455145835876, 'org:role_acc': 0.9603134393692017, 'case:Project_acc': 0.8963635563850403, 'case:Task_acc': 0.7571516036987305, 'case:OrganizationalEntity_acc': 0.9119865298271179, 'case:Activity_acc': 0.9910508990287781, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00758305912906373, 'case:RequestedAmount_mae': 0.1842693810661634, 'AVG_total_loss': 11.861983643529971, 'MAE_time:timestamp': 0.007683994248509407, 'MAE_case:RequestedAmount': 0.18528376519680023}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(
/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.018402173507884326, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:50:54] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:50:54] ax.service.managed_loop: Running optimization trial 43...
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:50:54] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9865354299545288, 'Activity_acc': 0.9270785450935364, 'org:role_acc': 0.9671313762664795, 'case:Project_acc': 0.8555107712745667, 'case:Task_acc': 0.7562321424484253, 'case:OrganizationalEntity_acc': 0.9110692143440247, 'case:Activity_acc': 0.993965744972229, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.007205135292477078, 'case:RequestedAmount_mae': 0.19680819577640957, 'AVG_total_loss': 11.998671803908008, 'MAE_time:timestamp': 0.007324830628931522, 'MAE_case:RequestedAmount': 0.1979513168334961}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.018904704985833794, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:54:13] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:54:13] ax.service.managed_loop: Running optimization trial 44...
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:54:13] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9832713007926941, 'Activity_acc': 0.9199084639549255, 'org:role_acc': 0.963620662689209, 'case:Project_acc': 0.843474268913269, 'case:Task_acc': 0.7546485662460327, 'case:OrganizationalEntity_acc': 0.8984813094139099, 'case:Activity_acc': 0.9912554621696472, 'case:RfpNumber_acc': 0.03955007344484329, 'time:timestamp_mae': 0.007651416688329644, 'case:RequestedAmount_mae': 0.1668500556714005, 'AVG_total_loss': 12.065799546731999, 'MAE_time:timestamp': 0.007733435835689306, 'MAE_case:RequestedAmount': 0.167470782995224}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.01964749128765731, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 14:58:06] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 14:58:06] ax.service.managed_loop: Running optimization trial 45...
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 14:58:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9772530198097229, 'Activity_acc': 0.9343503713607788, 'org:role_acc': 0.9615854620933533, 'case:Project_acc': 0.8899372816085815, 'case:Task_acc': 0.7536268830299377, 'case:OrganizationalEntity_acc': 0.9204974174499512, 'case:Activity_acc': 0.9931475520133972, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006900028230760385, 'case:RequestedAmount_mae': 0.17437407636532076, 'AVG_total_loss': 11.91701011063695, 'MAE_time:timestamp': 0.007012360729277134, 'MAE_case:RequestedAmount': 0.17522624135017395}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.019591656957405116, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 15:00:48] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 15:00:48] ax.service.managed_loop: Running optimization trial 46...
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:00:48] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9817922115325928, 'Activity_acc': 0.9285023808479309, 'org:role_acc': 0.9536481499671936, 'case:Project_acc': 0.8843269944190979, 'case:Task_acc': 0.7561299800872803, 'case:OrganizationalEntity_acc': 0.9035776257514954, 'case:Activity_acc': 0.9882894158363342, 'case:RfpNumber_acc': 0.0392908975481987, 'time:timestamp_mae': 0.006434887328564569, 'case:RequestedAmount_mae': 0.17443638377719456, 'AVG_total_loss': 11.981890041204341, 'MAE_time:timestamp': 0.006551909260451794, 'MAE_case:RequestedAmount': 0.1754790097475052}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.01906242199306218, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 15:04:06] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 15:04:06] ax.service.managed_loop: Running optimization trial 47...
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:04:06] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9842913150787354, 'Activity_acc': 0.9176709651947021, 'org:role_acc': 0.9657576084136963, 'case:Project_acc': 0.9003416895866394, 'case:Task_acc': 0.7586840987205505, 'case:OrganizationalEntity_acc': 0.8872693777084351, 'case:Activity_acc': 0.9902327060699463, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.00639458109314243, 'case:RequestedAmount_mae': 0.17489084904944455, 'AVG_total_loss': 11.937763329146913, 'MAE_time:timestamp': 0.006503158714622259, 'MAE_case:RequestedAmount': 0.17554156482219696}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.019074495428503504, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 15:10:55] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 15:10:55] ax.service.managed_loop: Running optimization trial 48...
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:10:55] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9714387655258179, 'Activity_acc': 0.9403508305549622, 'org:role_acc': 0.967436671257019, 'case:Project_acc': 0.8847350478172302, 'case:Task_acc': 0.7542909979820251, 'case:OrganizationalEntity_acc': 0.9151462912559509, 'case:Activity_acc': 0.9903349280357361, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.005991598216092421, 'case:RequestedAmount_mae': 0.12639832096519293, 'AVG_total_loss': 11.735282856932221, 'MAE_time:timestamp': 0.006109554786235094, 'MAE_case:RequestedAmount': 0.12770357728004456}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.018052666962204443, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 15:15:42] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 15:15:42] ax.service.managed_loop: Running optimization trial 49...
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:15:42] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9778650403022766, 'Activity_acc': 0.9428934454917908, 'org:role_acc': 0.9667243361473083, 'case:Project_acc': 0.903350830078125, 'case:Task_acc': 0.7536779642105103, 'case:OrganizationalEntity_acc': 0.9122923016548157, 'case:Activity_acc': 0.991715669631958, 'case:RfpNumber_acc': 0.03955007344484329, 'time:timestamp_mae': 0.006585279022584911, 'case:RequestedAmount_mae': 0.11782905969906736, 'AVG_total_loss': 12.002844527700088, 'MAE_time:timestamp': 0.006696158554404974, 'MAE_case:RequestedAmount': 0.11859067529439926}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.01869828317530326, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 15:17:50] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[INFO 11-12 15:17:50] ax.service.managed_loop: Running optimization trial 50...
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:17:50] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9858213663101196, 'Activity_acc': 0.9155352115631104, 'org:role_acc': 0.9619415998458862, 'case:Project_acc': 0.8211352825164795, 'case:Task_acc': 0.7536779642105103, 'case:OrganizationalEntity_acc': 0.9014881253242493, 'case:Activity_acc': 0.9935566186904907, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.007296583632490149, 'case:RequestedAmount_mae': 0.19593657166869552, 'AVG_total_loss': 12.38186636423537, 'MAE_time:timestamp': 0.007381976582109928, 'MAE_case:RequestedAmount': 0.19632087647914886}

/home/sebastiano.dissegna/AdaTest/v_env/lib/python3.12/site-packages/linear_operator/utils/cholesky.py:40: NumericalWarning: A not p.d., added jitter of 1.0e-08 to the diagonal
  warnings.warn(

{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.019480125717349497, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

[INFO 11-12 15:25:22] ax.core.experiment: Attached data has some metrics ({'MAE_time:timestamp', 'case:RequestedAmount_mae', 'case:RfpNumber_acc', 'Activity_acc', 'case:Task_acc', 'org:role_acc', 'case:OrganizationalEntity_acc', 'case:Activity_acc', 'time:timestamp_mae', 'MAE_case:RequestedAmount', 'org:resource_acc', 'case:Project_acc'}) that are not among the metrics on this experiment. Note that attaching data will not automatically add those metrics to the experiment. For these metrics to be automatically fetched by `experiment.fetch_data`, add them via `experiment.add_tracking_metric` or update the experiment's optimization config.
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:RfpNumber_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RfpNumber_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Task_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Task_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric org:resource_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:resource_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric org:role_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric org:role_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric time:timestamp_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric time:timestamp_mae.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_case:RequestedAmount that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_case:RequestedAmount.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric MAE_time:timestamp that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric MAE_time:timestamp.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Activity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Activity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:OrganizationalEntity_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:OrganizationalEntity_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:Project_acc that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:Project_acc.
NoneType: None
[ERROR 11-12 15:25:22] ax.core.observation: Data contains metric case:RequestedAmount_mae that has not been added to the experiment. You can either update the `optimization_config` or attach it as a tracking metric using `Experiment.add_tracking_metrics` or `AxClient.add_tracking_metrics`. Ignoring all data for metric case:RequestedAmount_mae.
NoneType: None

{'org:resource_acc': 0.9789360761642456, 'Activity_acc': 0.9444190263748169, 'org:role_acc': 0.9635697603225708, 'case:Project_acc': 0.9082470536231995, 'case:Task_acc': 0.7536268830299377, 'case:OrganizationalEntity_acc': 0.9010804295539856, 'case:Activity_acc': 0.9912554621696472, 'case:RfpNumber_acc': 0.03960190713405609, 'time:timestamp_mae': 0.006366417458694842, 'case:RequestedAmount_mae': 0.20591616327012027, 'AVG_total_loss': 11.88947294083536, 'MAE_time:timestamp': 0.006485761143267155, 'MAE_case:RequestedAmount': 0.2069842666387558}
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}
{'AVG_total_loss': 11.951471678514562}
Experiment(None)

In [28]:
from ax.service.utils.report_utils import exp_to_df

results = exp_to_df(experiment)

[WARNING 11-12 15:25:23] ax.service.utils.report_utils: Column reason missing for all trials. Not appending column.

In [29]:
results.sort_values(by="AVG_total_loss")

,trial_index,arm_name,trial_status,generation_method,AVG_total_loss,Activity_acc,MAE_case:RequestedAmount,MAE_time:timestamp,case:Activity_acc,case:OrganizationalEntity_acc,case:Project_acc,case:RequestedAmount_mae,case:RfpNumber_acc,case:Task_acc,org:resource_acc,org:role_acc,time:timestamp_mae,layers,lr,batch_size,weight_decay,aggregation,hid
46,46,46_0,COMPLETED,BoTorch,11.735283,0.940351,0.127704,0.006110,0.990335,0.915146,0.884735,0.126398,0.039602,0.754291,0.971439,0.967437,0.005992,4,0.010000,128,0.019074,sum,128
34,34,34_0,COMPLETED,BoTorch,11.839662,0.944724,0.125377,0.006458,0.992687,0.916064,0.901515,0.124329,0.039602,0.754444,0.980211,0.957820,0.006341,4,0.010000,128,0.022975,sum,128
40,40,40_0,COMPLETED,BoTorch,11.861984,0.937046,0.185284,0.007684,0.991051,0.911987,0.896364,0.184269,0.039602,0.757152,0.973020,0.960313,0.007583,4,0.010000,128,0.022416,sum,128
39,39,39_0,COMPLETED,BoTorch,11.878641,0.938012,0.156870,0.006835,0.987062,0.909031,0.881369,0.156214,0.039602,0.754444,0.976641,0.965809,0.006736,4,0.010000,128,0.022393,sum,128
49,49,49_0,COMPLETED,BoTorch,11.889473,0.944419,0.206984,0.006486,0.991255,0.901080,0.908247,0.205916,0.039602,0.753627,0.978936,0.963570,0.006366,4,0.010000,128,0.019480,sum,128
43,43,43_0,COMPLETED,BoTorch,11.917010,0.934350,0.175226,0.007012,0.993148,0.920497,0.889937,0.174374,0.039602,0.753627,0.977253,0.961585,0.006900,4,0.010000,128,0.019647,sum,128
11,11,11_0,COMPLETED,BoTorch,11.926921,0.947114,0.139186,0.006472,0.993761,0.912292,0.904932,0.138116,0.039602,0.753627,0.974805,0.956548,0.006353,4,0.010000,128,0.019508,sum,128
45,45,45_0,COMPLETED,BoTorch,11.937763,0.917671,0.175542,0.006503,0.990233,0.887269,0.900342,0.174891,0.039602,0.758684,0.984291,0.965758,0.006395,4,0.010000,128,0.019062,sum,128
44,44,44_0,COMPLETED,BoTorch,11.981890,0.928502,0.175479,0.006552,0.988289,0.903578,0.884327,0.174436,0.039291,0.756130,0.981792,0.953648,0.006435,4,0.010000,128,0.019592,sum,128
19,19,19_0,COMPLETED,BoTorch,11.990137,0.926112,0.195609,0.007245,0.992892,0.870808,0.899169,0.194220,0.039602,0.755466,0.980466,0.957769,0.007163,4,0.010000,128,0.019862,sum,128
35,35,35_0,COMPLETED,BoTorch,11.992833,0.939995,0.144465,0.006454,0.992943,0.872286,0.891059,0.143350,0.039602,0.754240,0.978222,0.956039,0.006336,4,0.010000,128,0.022800,sum,128
41,41,41_0,COMPLETED,BoTorch,11.998672,0.927079,0.197951,0.007325,0.993966,0.911069,0.855511,0.196808,0.039602,0.756232,0.986535,0.967131,0.007205,4,0.010000,128,0.018402,sum,128
47,47,47_0,COMPLETED,BoTorch,12.002845,0.942893,0.118591,0.006696,0.991716,0.912292,0.903351,0.117829,0.039550,0.753678,0.977865,0.966724,0.006585,4,0.010000,128,0.018053,sum,128
28,28,28_0,COMPLETED,BoTorch,12.004965,0.940859,0.182432,0.007645,0.992585,0.907757,0.891977,0.181136,0.039602,0.756130,0.972969,0.950901,0.007549,4,0.010000,128,0.023239,sum,128
30,30,30_0,COMPLETED,BoTorch,12.027759,0.947775,0.175887,0.006162,0.992636,0.897819,0.904983,0.174633,0.039602,0.754138,0.976233,0.956854,0.006048,4,0.010000,128,0.024030,sum,128
42,42,42_0,COMPLETED,BoTorch,12.065800,0.919908,0.167471,0.007733,0.991255,0.898481,0.843474,0.166850,0.039550,0.754649,0.983271,0.963621,0.007651,4,0.010000,128,0.018905,sum,128
24,24,24_0,COMPLETED,BoTorch,12.090822,0.941215,0.178351,0.006647,0.994733,0.883039,0.885449,0.177223,0.039602,0.753882,0.976335,0.954055,0.006536,4,0.010000,128,0.023782,sum,128
36,36,36_0,COMPLETED,BoTorch,12.099461,0.943758,0.180939,0.007587,0.989926,0.877841,0.891671,0.180086,0.039602,0.757049,0.977304,0.955124,0.007484,4,0.010000,128,0.022543,sum,128
29,29,29_0,COMPLETED,BoTorch,12.113623,0.944266,0.175908,0.009157,0.992892,0.873764,0.843729,0.174706,0.039602,0.756385,0.970317,0.952529,0.009090,4,0.010000,128,0.023771,sum,128
14,14,14_0,COMPLETED,BoTorch,12.155110,0.923061,0.186845,0.008015,0.995244,0.907400,0.837507,0.186502,0.039602,0.754597,0.978120,0.963163,0.007920,4,0.010000,128,0.017293,sum,128
32,32,32_0,COMPLETED,BoTorch,12.229905,0.933791,0.191414,0.009062,0.993608,0.917694,0.877748,0.190236,0.038928,0.755670,0.975111,0.952580,0.008971,4,0.010000,128,0.024071,sum,128
18,18,18_0,COMPLETED,BoTorch,12.243739,0.934554,0.135890,0.007480,0.992687,0.904189,0.889325,0.134707,0.039602,0.754700,0.976947,0.959194,0.007364,4,0.010000,128,0.018579,sum,128
31,31,31_0,COMPLETED,BoTorch,12.247319,0.923366,0.137129,0.006917,0.987471,0.914382,0.851329,0.136090,0.039602,0.756130,0.970113,0.947186,0.006814,4,0.010000,128,0.024224,sum,128
33,33,33_0,COMPLETED,BoTorch,12.249020,0.929672,0.147658,0.006268,0.975658,0.914076,0.840057,0.146433,0.039602,0.756130,0.967869,0.953699,0.006153,4,0.010000,128,0.022935,sum,128
38,38,38_0,COMPLETED,BoTorch,12.332022,0.931757,0.273159,0.006357,0.992994,0.868311,0.891212,0.271728,0.039602,0.757611,0.972918,0.951715,0.006248,4,0.010000,128,0.022621,sum,128
25,25,25_0,COMPLETED,BoTorch,12.346446,0.913552,0.186848,0.006249,0.990182,0.866884,0.812516,0.186279,0.039602,0.756896,0.976896,0.952427,0.006134,4,0.010000,128,0.027120,sum,128
12,12,12_0,COMPLETED,BoTorch,12.352107,0.912382,0.212058,0.013441,0.991562,0.877026,0.828480,0.211122,0.039602,0.755875,0.982557,0.956803,0.013390,4,0.010000,128,0.023955,sum,128
48,48,48_0,COMPLETED,BoTorch,12.381866,0.915535,0.196321,0.007382,0.993557,0.901488,0.821135,0.195937,0.039602,0.753678,0.985821,0.961942,0.007297,4,0.010000,128,0.018698,sum,128
37,37,37_0,COMPLETED,BoTorch,12.497725,0.913145,0.207013,0.008015,0.992687,0.856946,0.842913,0.205323,0.039602,0.754189,0.979854,0.954106,0.007922,4,0.010000,128,0.023388,sum,128
17,17,17_0,COMPLETED,BoTorch,12.577825,0.924434,0.129330,0.006842,0.985272,0.886811,0.876626,0.128090,0.039602,0.754700,0.965982,0.943167,0.006713,2,0.010000,128,0.010000,sum,128
27,27,27_0,COMPLETED,BoTorch,12.731691,0.924587,0.263497,0.006863,0.988136,0.861992,0.828582,0.262469,0.039602,0.755466,0.976743,0.898596,0.006746,4,0.010000,128,0.026781,sum,128
20,20,20_0,COMPLETED,BoTorch,12.733661,0.922248,0.121701,0.006124,0.994733,0.867088,0.876269,0.121008,0.038824,0.759604,0.977967,0.952681,0.006019,4,0.010000,128,0.010000,max,128
15,15,15_0,COMPLETED,BoTorch,12.743022,0.910857,0.175737,0.006628,0.987062,0.879574,0.833019,0.174475,0.039602,0.754036,0.954710,0.926173,0.006504,2,0.010000,128,0.010000,max,128
26,26,26_0,COMPLETED,BoTorch,12.984205,0.912179,0.154500,0.007280,0.987062,0.882887,0.859540,0.154390,0.039602,0.754393,0.962768,0.942200,0.007168,2,0.010000,512,0.010000,sum,128
9,9,9_0,COMPLETED,Sobol,13.027219,0.920976,0.161992,0.016813,0.980670,0.888849,0.882593,0.161216,0.039395,0.755108,0.977457,0.954818,0.016704,4,0.000712,128,0.016368,sum,128
10,10,10_0,COMPLETED,BoTorch,13.105389,0.923163,0.188982,0.006804,0.993301,0.874223,0.891212,0.187937,0.039291,0.755517,0.984291,0.965809,0.006698,4,0.010000,512,0.017456,sum,128
13,13,13_0,COMPLETED,BoTorch,13.239177,0.866107,0.198498,0.006404,0.964664,0.848333,0.791605,0.197389,0.039602,0.755977,0.965726,0.937061,0.006292,2,0.010000,128,0.019861,sum,128
16,16,16_0,COMPLETED,BoTorch,13.302194,0.902924,0.129607,0.006444,0.987062,0.869789,0.857398,0.128796,0.039602,0.753780,0.956444,0.923832,0.006326,2,0.010000,512,0.010000,max,128
4,4,4_0,COMPLETED,Sobol,13.398104,0.914722,0.232874,0.006827,0.966096,0.873153,0.842454,0.232821,0.039602,0.755517,0.961646,0.938842,0.006718,2,0.006799,512,0.014659,sum,128
23,23,23_0,COMPLETED,BoTorch,13.554117,0.891126,0.109363,0.007953,0.987062,0.826470,0.754526,0.108672,0.039602,0.753627,0.953486,0.909281,0.007845,2,0.010000,128,0.018376,max,128
3,3,3_0,COMPLETED,Sobol,13.851181,0.922400,0.148501,0.006265,0.987062,0.868923,0.852145,0.147522,0.039602,0.755823,0.961442,0.941386,0.006181,2,0.000880,256,0.012815,sum,128
21,21,21_0,COMPLETED,BoTorch,14.302577,0.901754,0.075550,0.006585,0.987062,0.835797,0.768501,0.074679,0.039602,0.753780,0.958688,0.920881,0.006463,2,0.000100,128,0.015269,max,128
8,8,8_0,COMPLETED,Sobol,15.029672,0.823239,0.101606,0.006721,0.979903,0.774233,0.580048,0.100801,0.039602,0.753627,0.932218,0.905465,0.006616,2,0.003285,256,0.033006,max,128
7,7,7_0,COMPLETED,Sobol,16.111480,0.871192,0.155705,0.006706,0.987062,0.678779,0.416076,0.155229,0.039602,0.753627,0.931504,0.887402,0.006594,2,0.000113,128,0.062957,sum,128
0,0,0_0,COMPLETED,Sobol,17.532494,0.823392,0.252472,0.006710,0.982051,0.220620,0.277044,0.252385,0.039602,0.753627,0.931147,0.822733,0.006602,2,0.001453,256,0.097871,sum,128
1,1,1_0,COMPLETED,Sobol,17.605425,0.873888,0.080363,0.045260,0.992790,0.603965,0.159331,0.079740,0.039602,0.755415,0.974958,0.941081,0.045387,4,0.000294,512,0.020456,max,128
2,2,2_0,COMPLETED,Sobol,17.871519,0.833918,0.173163,0.007762,0.984352,0.085109,0.099046,0.172568,0.039602,0.753627,0.966645,0.817900,0.007659,4,0.004854,128,0.045972,max,128
6,6,6_0,COMPLETED,Sobol,18.233775,0.877142,0.164345,0.037705,0.993403,0.110641,0.134952,0.163589,0.039602,0.751941,0.977457,0.929277,0.037877,4,0.002114,512,0.031204,max,128
5,5,5_0,COMPLETED,Sobol,18.716797,0.819425,0.083870,0.033204,0.990897,0.129752,0.140511,0.083098,0.039602,0.753269,0.972816,0.910960,0.033109,4,0.000350,256,0.039437,max,128
22,22,22_0,COMPLETED,BoTorch,19.724982,0.457462,0.133128,0.007774,0.978880,0.111457,0.098995,0.132270,0.039602,0.753627,0.886520,0.689987,0.007704,2,0.000100,128,0.100000,max,128

In [30]:
results = results.sort_values(by="AVG_total_loss")

In [31]:
results.to_csv(f"results/results_CAISE/{dataset}_CONFIGS.csv", sep=",")

## Test on different test sets

In [32]:
test_types = ["even", "odd", "window", "random", "attr_level"]

In [33]:
import pandas


def create_df(results):
    res = {}
    
    for k in results[0]:
        res[k] = [x[k] for x in results]
    
    res = pandas.DataFrame(data=res)
    
    return res, res.mean(), res.std()

In [34]:
def test_multi(config, outputcat, outputreal, num_runs=10, num_epochs=20):
    
    res = {}
    
    save_path = f"results/results_CAISE/{dataset}/"
    
    if not os.path.isdir(save_path):
        os.makedirs(save_path)
    
    for i in range(num_runs):
        
        print(f"Run {i}")
        
        net = train_hgnn(
                config, 
                outputcat,
                outputreal,
                num_epochs
            )
        
        
        
        for test_type in test_types:
            
            print(f"Test type {test_type}")
            
            with open(data_dir_graphs + dataset + f"_TEST_V2_repair_{test_type}.pkl", "rb") as f:
                X = pickle.load(f)    
                
            for i in range(len(X)):
                X[i] = transform(X[i])

            if test_type not in res:
                res[test_type] = []
            
           
                
            
                
            res[test_type].append(
                test_hgnn(
                    net,
                    outputcat,
                    outputreal,
                    test_graphs=X
                )
            )
    
    for test_type in test_types:    
        results_table, means, stds = create_df(res[test_type])
                
        results_table.to_csv(f"{save_path}{test_type}_V2_RESULTS_END.csv", sep=",", index=False)
        
        pd.DataFrame(data={"mean" : means, "std" : stds}).to_csv(f"{save_path}{test_type}_V2_MEAN_STD_END.csv", sep=",")
        
        print(test_type)
        print(pd.DataFrame(data={"mean" : means, "std" : stds}))
        
        
    
    return res

In [ ]:
dataset

In [ ]:
best_parameters

In [35]:
res = test_multi(best_parameters, outputcat, outputreal, 10, 100)

Run 0
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 1.0, 'Activity_acc': 0.9672920107841492, 'org:role_acc': 0.9918230175971985, 'case:Project_acc': 0.9367484450340271, 'case:Task_acc': 0.7561327815055847, 'case:OrganizationalEntity_acc': 0.9514189958572388, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.00896613435311751, 'case:RequestedAmount_mae': 0.04669454896991903, 'AVG_total_loss': 11.46605064959096, 'MAE_time:timestamp': 0.008677461184561253, 'MAE_case:RequestedAmount': 0.04690558463335037}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.9637243151664734, 'org:role_acc': 0.9924426078796387, 'case:Project_acc': 0.9319831132888794, 'case:Task_acc': 0.7551390528678894, 'case:OrganizationalEntity_acc': 0.9489117860794067, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.009411917195062746, 'case:RequestedAmount_mae': 0.06112187321890484, 'AVG_total_loss': 11.800626447985202, 'MAE_time:timestamp': 0.009161784313619137, 'MAE_case:RequestedAmount': 0.0611051507294178}
Test type window
{'org:resource_acc': 0.9987239241600037, 'Activity_acc': 0.9413015842437744, 'org:role_acc': 0.9925563335418701, 'case:Project_acc': 0.9323691725730896, 'case:Task_acc': 0.7554231882095337, 'case:OrganizationalEntity_acc': 0.947469174861908, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.01074026973748749, 'case:RequestedAmount_mae': 0.12718902189623227, 'AVG_total_loss': 11.753549907822162, 'MAE_time:timestamp': 0.010441993363201618, 'MAE_case:RequestedAmount': 0.12748196721076965}
Test type random
{'org:resource_acc': 0.9297253489494324, 'Activity_acc': 0.7905223369598389, 'org:role_acc': 0.8629509806632996, 'case:Project_acc': 0.8519116640090942, 'case:Task_acc': 0.7550525069236755, 'case:OrganizationalEntity_acc': 0.8236402273178101, 'case:Activity_acc': 0.981152355670929, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.009066368410871788, 'case:RequestedAmount_mae': 0.2358381301164627, 'AVG_total_loss': 13.465420739598233, 'MAE_time:timestamp': 0.00880534015595913, 'MAE_case:RequestedAmount': 0.23539917171001434}
Test type attr_level
{'org:resource_acc': 0.9916778802871704, 'Activity_acc': 0.9135606288909912, 'org:role_acc': 0.9631495475769043, 'case:Project_acc': 0.8287248611450195, 'case:Task_acc': 0.7598052024841309, 'case:OrganizationalEntity_acc': 0.8441176414489746, 'case:Activity_acc': 0.9695072770118713, 'case:RfpNumber_acc': 0.03448275849223137, 'time:timestamp_mae': 0.009529068261723627, 'case:RequestedAmount_mae': 0.27405209974809125, 'AVG_total_loss': 13.039065406615423, 'MAE_time:timestamp': 0.009269017726182938, 'MAE_case:RequestedAmount': 0.27335160970687866}
Run 1
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 0.9995189905166626, 'Activity_acc': 0.9694564938545227, 'org:role_acc': 0.9920635223388672, 'case:Project_acc': 0.941077470779419, 'case:Task_acc': 0.7570948004722595, 'case:OrganizationalEntity_acc': 0.9540644884109497, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.005737222053787925, 'case:RequestedAmount_mae': 0.10044380277395248, 'AVG_total_loss': 11.15396140712652, 'MAE_time:timestamp': 0.005589568056166172, 'MAE_case:RequestedAmount': 0.10030018538236618}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.9866989254951477, 'org:role_acc': 0.9927449226379395, 'case:Project_acc': 0.9365175366401672, 'case:Task_acc': 0.7533252835273743, 'case:OrganizationalEntity_acc': 0.9489117860794067, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.006262020800601353, 'case:RequestedAmount_mae': 0.08987421610138634, 'AVG_total_loss': 11.35674003323286, 'MAE_time:timestamp': 0.006123069208115339, 'MAE_case:RequestedAmount': 0.08969634026288986}
Test type window
{'org:resource_acc': 0.996597170829773, 'Activity_acc': 0.9793704748153687, 'org:role_acc': 0.9912803173065186, 'case:Project_acc': 0.9336452484130859, 'case:Task_acc': 0.753296434879303, 'case:OrganizationalEntity_acc': 0.947043776512146, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.006667808756570925, 'case:RequestedAmount_mae': 0.06903915378180417, 'AVG_total_loss': 11.497180348600853, 'MAE_time:timestamp': 0.006476354785263538, 'MAE_case:RequestedAmount': 0.06903570890426636}
Test type random
{'org:resource_acc': 0.8715670108795166, 'Activity_acc': 0.8408723473548889, 'org:role_acc': 0.8874528408050537, 'case:Project_acc': 0.8397953510284424, 'case:Task_acc': 0.7550525069236755, 'case:OrganizationalEntity_acc': 0.878298282623291, 'case:Activity_acc': 0.969574511051178, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.006976528474214402, 'case:RequestedAmount_mae': 0.2539543143727563, 'AVG_total_loss': 13.10520134023814, 'MAE_time:timestamp': 0.006782389245927334, 'MAE_case:RequestedAmount': 0.25395941734313965}
Test type attr_level
{'org:resource_acc': 0.9873825907707214, 'Activity_acc': 0.9376156330108643, 'org:role_acc': 0.9695122241973877, 'case:Project_acc': 0.8182550668716431, 'case:Task_acc': 0.7595347166061401, 'case:OrganizationalEntity_acc': 0.8609625697135925, 'case:Activity_acc': 0.961884081363678, 'case:RfpNumber_acc': 0.038687970489263535, 'time:timestamp_mae': 0.006240928841924126, 'case:RequestedAmount_mae': 0.2576437998901714, 'AVG_total_loss': 12.736312718511643, 'MAE_time:timestamp': 0.006097413599491119, 'MAE_case:RequestedAmount': 0.25691157579421997}
Run 2
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 1.0, 'Activity_acc': 0.9639250040054321, 'org:role_acc': 0.9944685101509094, 'case:Project_acc': 0.9425204396247864, 'case:Task_acc': 0.7544492483139038, 'case:OrganizationalEntity_acc': 0.9615199565887451, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.00773672911931168, 'case:RequestedAmount_mae': 0.08960010043599388, 'AVG_total_loss': 10.889359136217866, 'MAE_time:timestamp': 0.007570880930870771, 'MAE_case:RequestedAmount': 0.08963961154222488}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.9325876832008362, 'org:role_acc': 0.9543530941009521, 'case:Project_acc': 0.9404474496841431, 'case:Task_acc': 0.75, 'case:OrganizationalEntity_acc': 0.9588875770568848, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.006050537763671441, 'case:RequestedAmount_mae': 0.07345802269198677, 'AVG_total_loss': 11.2149092742316, 'MAE_time:timestamp': 0.005949856713414192, 'MAE_case:RequestedAmount': 0.07348380982875824}
Test type window
{'org:resource_acc': 0.9993619918823242, 'Activity_acc': 0.9349213242530823, 'org:role_acc': 0.9891535639762878, 'case:Project_acc': 0.9413015842437744, 'case:Task_acc': 0.7530837655067444, 'case:OrganizationalEntity_acc': 0.9517226815223694, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.006460273680700498, 'case:RequestedAmount_mae': 0.1448712240565907, 'AVG_total_loss': 11.394914283713495, 'MAE_time:timestamp': 0.006266371812671423, 'MAE_case:RequestedAmount': 0.14519785344600677}
Test type random
{'org:resource_acc': 0.8936456441879272, 'Activity_acc': 0.8435648679733276, 'org:role_acc': 0.8971458673477173, 'case:Project_acc': 0.8575659394264221, 'case:Task_acc': 0.7531662583351135, 'case:OrganizationalEntity_acc': 0.8535271286964417, 'case:Activity_acc': 0.9851911067962646, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.007882958024062893, 'case:RequestedAmount_mae': 0.35257231376387854, 'AVG_total_loss': 12.9752154041251, 'MAE_time:timestamp': 0.0077069103717803955, 'MAE_case:RequestedAmount': 0.3522424101829529}
Test type attr_level
{'org:resource_acc': 0.9930201768875122, 'Activity_acc': 0.9122388958930969, 'org:role_acc': 0.9716331362724304, 'case:Project_acc': 0.8383892774581909, 'case:Task_acc': 0.7573708295822144, 'case:OrganizationalEntity_acc': 0.8417112231254578, 'case:Activity_acc': 0.9823033213615417, 'case:RfpNumber_acc': 0.038687970489263535, 'time:timestamp_mae': 0.007613019467416135, 'case:RequestedAmount_mae': 0.3420351662419059, 'AVG_total_loss': 12.596650171305306, 'MAE_time:timestamp': 0.007510690484195948, 'MAE_case:RequestedAmount': 0.34202420711517334}
Run 3
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 1.0, 'Activity_acc': 0.9680134654045105, 'org:role_acc': 0.9923040270805359, 'case:Project_acc': 0.9369889497756958, 'case:Task_acc': 0.7539682388305664, 'case:OrganizationalEntity_acc': 0.9506974816322327, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.007126885931938887, 'case:RequestedAmount_mae': 0.09317779405550523, 'AVG_total_loss': 10.91664375834675, 'MAE_time:timestamp': 0.006969604641199112, 'MAE_case:RequestedAmount': 0.09337407350540161}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.9791415333747864, 'org:role_acc': 0.9897218942642212, 'case:Project_acc': 0.9334945678710938, 'case:Task_acc': 0.75, 'case:OrganizationalEntity_acc': 0.9467957019805908, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.006316196723756465, 'case:RequestedAmount_mae': 0.060769142413681206, 'AVG_total_loss': 11.080634348888204, 'MAE_time:timestamp': 0.006200939416885376, 'MAE_case:RequestedAmount': 0.06098032370209694}
Test type window
{'org:resource_acc': 0.9997873306274414, 'Activity_acc': 0.9523606896400452, 'org:role_acc': 0.990642249584198, 'case:Project_acc': 0.9296044111251831, 'case:Task_acc': 0.7526584267616272, 'case:OrganizationalEntity_acc': 0.9451297521591187, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.006910807453095913, 'case:RequestedAmount_mae': 0.12148235467347232, 'AVG_total_loss': 11.233260283246636, 'MAE_time:timestamp': 0.006730854045599699, 'MAE_case:RequestedAmount': 0.12181294709444046}
Test type random
{'org:resource_acc': 0.8931071162223816, 'Activity_acc': 0.8058696389198303, 'org:role_acc': 0.8758749961853027, 'case:Project_acc': 0.851642370223999, 'case:Task_acc': 0.752896785736084, 'case:OrganizationalEntity_acc': 0.8597199320793152, 'case:Activity_acc': 0.9851911067962646, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.007896356369284067, 'case:RequestedAmount_mae': 0.27416839653795416, 'AVG_total_loss': 13.06643798109144, 'MAE_time:timestamp': 0.007714146748185158, 'MAE_case:RequestedAmount': 0.27384376525878906}
Test type attr_level
{'org:resource_acc': 0.9841610789299011, 'Activity_acc': 0.9127675890922546, 'org:role_acc': 0.9565218091011047, 'case:Project_acc': 0.8198657631874084, 'case:Task_acc': 0.7584527730941772, 'case:OrganizationalEntity_acc': 0.8665775656700134, 'case:Activity_acc': 0.9806697964668274, 'case:RfpNumber_acc': 0.038687970489263535, 'time:timestamp_mae': 0.007350378204137087, 'case:RequestedAmount_mae': 0.29260154881260614, 'AVG_total_loss': 12.492668489459902, 'MAE_time:timestamp': 0.007249068468809128, 'MAE_case:RequestedAmount': 0.292812705039978}
Run 4
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 0.9995189905166626, 'Activity_acc': 0.9656084775924683, 'org:role_acc': 0.9911015033721924, 'case:Project_acc': 0.9184704422950745, 'case:Task_acc': 0.7539682388305664, 'case:OrganizationalEntity_acc': 0.9499759674072266, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.0066370483995838595, 'case:RequestedAmount_mae': 0.06456259536472234, 'AVG_total_loss': 11.396905264542015, 'MAE_time:timestamp': 0.006364607717841864, 'MAE_case:RequestedAmount': 0.0647723525762558}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.9570738077163696, 'org:role_acc': 0.9909310936927795, 'case:Project_acc': 0.9201934933662415, 'case:Task_acc': 0.75, 'case:OrganizationalEntity_acc': 0.94649338722229, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.007235275920141827, 'case:RequestedAmount_mae': 0.05142285607077859, 'AVG_total_loss': 11.649011847785335, 'MAE_time:timestamp': 0.0070282225497066975, 'MAE_case:RequestedAmount': 0.05132204294204712}
Test type window
{'org:resource_acc': 0.9980859160423279, 'Activity_acc': 0.9461930990219116, 'org:role_acc': 0.9938324093818665, 'case:Project_acc': 0.8987664580345154, 'case:Task_acc': 0.7526584267616272, 'case:OrganizationalEntity_acc': 0.9198213219642639, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.007510654924606735, 'case:RequestedAmount_mae': 0.14092584834857422, 'AVG_total_loss': 11.764634166209197, 'MAE_time:timestamp': 0.007235473021864891, 'MAE_case:RequestedAmount': 0.14131411910057068}
Test type random
{'org:resource_acc': 0.9372643828392029, 'Activity_acc': 0.7940225601196289, 'org:role_acc': 0.8758749961853027, 'case:Project_acc': 0.7891760468482971, 'case:Task_acc': 0.752896785736084, 'case:OrganizationalEntity_acc': 0.8222939968109131, 'case:Activity_acc': 0.981152355670929, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.007421128494157033, 'case:RequestedAmount_mae': 0.2853496697815982, 'AVG_total_loss': 13.436378116592426, 'MAE_time:timestamp': 0.0071763889864087105, 'MAE_case:RequestedAmount': 0.2859093248844147}
Test type attr_level
{'org:resource_acc': 0.9951677918434143, 'Activity_acc': 0.9196404814720154, 'org:role_acc': 0.9618239998817444, 'case:Project_acc': 0.7664429545402527, 'case:Task_acc': 0.758723258972168, 'case:OrganizationalEntity_acc': 0.7668449282646179, 'case:Activity_acc': 0.9714130759239197, 'case:RfpNumber_acc': 0.03784693032503128, 'time:timestamp_mae': 0.007849738425151869, 'case:RequestedAmount_mae': 0.31905094195495953, 'AVG_total_loss': 13.373418882658536, 'MAE_time:timestamp': 0.007685786113142967, 'MAE_case:RequestedAmount': 0.3184809982776642}
Run 5
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 1.0, 'Activity_acc': 0.9675325155258179, 'org:role_acc': 0.9901394844055176, 'case:Project_acc': 0.936026930809021, 'case:Task_acc': 0.7582972645759583, 'case:OrganizationalEntity_acc': 0.9314574599266052, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.0058025621216405525, 'case:RequestedAmount_mae': 0.06319986961104652, 'AVG_total_loss': 11.2596592271637, 'MAE_time:timestamp': 0.005652234889566898, 'MAE_case:RequestedAmount': 0.06313104927539825}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.9791415333747864, 'org:role_acc': 0.9815598726272583, 'case:Project_acc': 0.932889997959137, 'case:Task_acc': 0.7542321681976318, 'case:OrganizationalEntity_acc': 0.927146315574646, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.00668609764596278, 'case:RequestedAmount_mae': 0.0320378802716732, 'AVG_total_loss': 11.494762156629639, 'MAE_time:timestamp': 0.006597904488444328, 'MAE_case:RequestedAmount': 0.032037705183029175}
Test type window
{'org:resource_acc': 0.9982985854148865, 'Activity_acc': 0.9774563908576965, 'org:role_acc': 0.9870268106460571, 'case:Project_acc': 0.9123777151107788, 'case:Task_acc': 0.75669926404953, 'case:OrganizationalEntity_acc': 0.9247128963470459, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.006574076600372791, 'case:RequestedAmount_mae': 0.12055678259242665, 'AVG_total_loss': 11.595226871738719, 'MAE_time:timestamp': 0.006388740614056587, 'MAE_case:RequestedAmount': 0.12060428410768509}
Test type random
{'org:resource_acc': 0.9334948658943176, 'Activity_acc': 0.8072159290313721, 'org:role_acc': 0.9001076817512512, 'case:Project_acc': 0.8217554688453674, 'case:Task_acc': 0.7545135617256165, 'case:OrganizationalEntity_acc': 0.8341410756111145, 'case:Activity_acc': 0.9841141104698181, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.007488514423709024, 'case:RequestedAmount_mae': 0.23230394314635883, 'AVG_total_loss': 13.170919487633826, 'MAE_time:timestamp': 0.0073088835924863815, 'MAE_case:RequestedAmount': 0.23225197196006775}
Test type attr_level
{'org:resource_acc': 0.9924832582473755, 'Activity_acc': 0.9233412146568298, 'org:role_acc': 0.9726935625076294, 'case:Project_acc': 0.7903355956077576, 'case:Task_acc': 0.7608871459960938, 'case:OrganizationalEntity_acc': 0.8104278445243835, 'case:Activity_acc': 0.9765859246253967, 'case:RfpNumber_acc': 0.03756657987833023, 'time:timestamp_mae': 0.007061770820820873, 'case:RequestedAmount_mae': 0.26954578946937213, 'AVG_total_loss': 12.961242115929384, 'MAE_time:timestamp': 0.006947004236280918, 'MAE_case:RequestedAmount': 0.2688935399055481}
Run 6
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 0.9995189905166626, 'Activity_acc': 0.9588744640350342, 'org:role_acc': 0.9920635223388672, 'case:Project_acc': 0.9338624477386475, 'case:Task_acc': 0.755892276763916, 'case:OrganizationalEntity_acc': 0.9480519890785217, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.007461957083168355, 'case:RequestedAmount_mae': 0.09769094261256131, 'AVG_total_loss': 11.358822654509408, 'MAE_time:timestamp': 0.007414435036480427, 'MAE_case:RequestedAmount': 0.09763683378696442}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.978234589099884, 'org:role_acc': 0.9924426078796387, 'case:Project_acc': 0.9301693439483643, 'case:Task_acc': 0.7524183988571167, 'case:OrganizationalEntity_acc': 0.9419589042663574, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.007745974697172642, 'case:RequestedAmount_mae': 0.10374555398117412, 'AVG_total_loss': 11.658544602470515, 'MAE_time:timestamp': 0.007727290038019419, 'MAE_case:RequestedAmount': 0.10376083850860596}
Test type window
{'org:resource_acc': 0.9963845014572144, 'Activity_acc': 0.9323691725730896, 'org:role_acc': 0.9900042414665222, 'case:Project_acc': 0.9268396496772766, 'case:Task_acc': 0.7541471719741821, 'case:OrganizationalEntity_acc': 0.9387494325637817, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.008413866712627087, 'case:RequestedAmount_mae': 0.10644158720970154, 'AVG_total_loss': 11.635899483078076, 'MAE_time:timestamp': 0.008336946368217468, 'MAE_case:RequestedAmount': 0.10678167641162872}
Test type random
{'org:resource_acc': 0.9243403077125549, 'Activity_acc': 0.8414108157157898, 'org:role_acc': 0.8656434416770935, 'case:Project_acc': 0.8438341021537781, 'case:Task_acc': 0.7542440891265869, 'case:OrganizationalEntity_acc': 0.8505653738975525, 'case:Activity_acc': 0.9851911067962646, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.008435391058976, 'case:RequestedAmount_mae': 0.2662341012196107, 'AVG_total_loss': 13.200989435003562, 'MAE_time:timestamp': 0.008352336473762989, 'MAE_case:RequestedAmount': 0.26714831590652466}
Test type attr_level
{'org:resource_acc': 0.9887248277664185, 'Activity_acc': 0.929421067237854, 'org:role_acc': 0.9679215550422668, 'case:Project_acc': 0.8214765191078186, 'case:Task_acc': 0.7538544535636902, 'case:OrganizationalEntity_acc': 0.8334224820137024, 'case:Activity_acc': 0.9735910892486572, 'case:RfpNumber_acc': 0.038687970489263535, 'time:timestamp_mae': 0.01039461334320632, 'case:RequestedAmount_mae': 0.27320382676341315, 'AVG_total_loss': 13.000039143995805, 'MAE_time:timestamp': 0.010425725020468235, 'MAE_case:RequestedAmount': 0.2727839946746826}
Run 7
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 0.9997594952583313, 'Activity_acc': 0.9684944748878479, 'org:role_acc': 0.9947090148925781, 'case:Project_acc': 0.9405964612960815, 'case:Task_acc': 0.7554112672805786, 'case:OrganizationalEntity_acc': 0.9160654544830322, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.005728889574212107, 'case:RequestedAmount_mae': 0.055020289664918724, 'AVG_total_loss': 11.252926186065782, 'MAE_time:timestamp': 0.005483168642967939, 'MAE_case:RequestedAmount': 0.05493857339024544}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.9631197452545166, 'org:role_acc': 0.990024209022522, 'case:Project_acc': 0.9383313655853271, 'case:Task_acc': 0.7512091994285583, 'case:OrganizationalEntity_acc': 0.9105199575424194, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.007462519094009291, 'case:RequestedAmount_mae': 0.056019772521474144, 'AVG_total_loss': 11.549835752177222, 'MAE_time:timestamp': 0.00727638928219676, 'MAE_case:RequestedAmount': 0.055731769651174545}
Test type window
{'org:resource_acc': 0.9980859160423279, 'Activity_acc': 0.9430029392242432, 'org:role_acc': 0.9919183254241943, 'case:Project_acc': 0.9140791296958923, 'case:Task_acc': 0.7539345026016235, 'case:OrganizationalEntity_acc': 0.9153551459312439, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.008253613825548779, 'case:RequestedAmount_mae': 0.07889593257145448, 'AVG_total_loss': 11.594250978838483, 'MAE_time:timestamp': 0.007978025823831558, 'MAE_case:RequestedAmount': 0.07907582819461823}
Test type random
{'org:resource_acc': 0.9240710139274597, 'Activity_acc': 0.7899838089942932, 'org:role_acc': 0.8586429357528687, 'case:Project_acc': 0.8120624423027039, 'case:Task_acc': 0.7539746165275574, 'case:OrganizationalEntity_acc': 0.8317177891731262, 'case:Activity_acc': 0.981152355670929, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.007507090795446526, 'case:RequestedAmount_mae': 0.26083892583847046, 'AVG_total_loss': 13.374887546270408, 'MAE_time:timestamp': 0.007269111927598715, 'MAE_case:RequestedAmount': 0.26133325695991516}
Test type attr_level
{'org:resource_acc': 0.9938254952430725, 'Activity_acc': 0.9159396886825562, 'org:role_acc': 0.9679215550422668, 'case:Project_acc': 0.8002684712409973, 'case:Task_acc': 0.7589937448501587, 'case:OrganizationalEntity_acc': 0.812566876411438, 'case:Activity_acc': 0.9692350029945374, 'case:RfpNumber_acc': 0.03784693032503128, 'time:timestamp_mae': 0.007199459370564331, 'case:RequestedAmount_mae': 0.2924471389163624, 'AVG_total_loss': 12.97943912107836, 'MAE_time:timestamp': 0.007011044770479202, 'MAE_case:RequestedAmount': 0.2916245758533478}
Run 8
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 0.9995189905166626, 'Activity_acc': 0.9684944748878479, 'org:role_acc': 0.9915825128555298, 'case:Project_acc': 0.945406436920166, 'case:Task_acc': 0.7568542957305908, 'case:OrganizationalEntity_acc': 0.9526214599609375, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.0073779931884597645, 'case:RequestedAmount_mae': 0.05109399049119516, 'AVG_total_loss': 10.95847941759381, 'MAE_time:timestamp': 0.007088411133736372, 'MAE_case:RequestedAmount': 0.05118352919816971}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.9637243151664734, 'org:role_acc': 0.9918379783630371, 'case:Project_acc': 0.9401451349258423, 'case:Task_acc': 0.755743682384491, 'case:OrganizationalEntity_acc': 0.9498186707496643, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.00858039887283336, 'case:RequestedAmount_mae': 0.04152404991063205, 'AVG_total_loss': 11.211765069742052, 'MAE_time:timestamp': 0.008338134735822678, 'MAE_case:RequestedAmount': 0.041573941707611084}
Test type window
{'org:resource_acc': 0.9980859160423279, 'Activity_acc': 0.9551254510879517, 'org:role_acc': 0.9885154962539673, 'case:Project_acc': 0.9423649311065674, 'case:Task_acc': 0.7543598413467407, 'case:OrganizationalEntity_acc': 0.9417269229888916, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.008838973389091816, 'case:RequestedAmount_mae': 0.06149428913539106, 'AVG_total_loss': 11.273581261958249, 'MAE_time:timestamp': 0.00854174792766571, 'MAE_case:RequestedAmount': 0.06161600723862648}
Test type random
{'org:resource_acc': 0.940226137638092, 'Activity_acc': 0.8047926425933838, 'org:role_acc': 0.893376350402832, 'case:Project_acc': 0.8527194261550903, 'case:Task_acc': 0.7550525069236755, 'case:OrganizationalEntity_acc': 0.871836245059967, 'case:Activity_acc': 0.9585352540016174, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.007828002456914295, 'case:RequestedAmount_mae': 0.21142657507549634, 'AVG_total_loss': 12.943086287345398, 'MAE_time:timestamp': 0.007560469675809145, 'MAE_case:RequestedAmount': 0.2110021710395813}
Test type attr_level
{'org:resource_acc': 0.9932886362075806, 'Activity_acc': 0.9172613620758057, 'org:role_acc': 0.9732238054275513, 'case:Project_acc': 0.8405369520187378, 'case:Task_acc': 0.7589937448501587, 'case:OrganizationalEntity_acc': 0.8633689880371094, 'case:Activity_acc': 0.9471821784973145, 'case:RfpNumber_acc': 0.038687970489263535, 'time:timestamp_mae': 0.007682944012975151, 'case:RequestedAmount_mae': 0.24408415772698142, 'AVG_total_loss': 12.555503060152246, 'MAE_time:timestamp': 0.00742650032043457, 'MAE_case:RequestedAmount': 0.24434296786785126}
Run 9
{'layers': 4, 'lr': 0.01, 'batch_size': 128, 'weight_decay': 0.0172933458234693, 'aggregation': 'sum', 'hid': 128}

  0%|          | 0/100 [00:00<?, ?it/s]

Test type even
{'org:resource_acc': 1.0, 'Activity_acc': 0.969215989112854, 'org:role_acc': 0.9927850365638733, 'case:Project_acc': 0.93241947889328, 'case:Task_acc': 0.7539682388305664, 'case:OrganizationalEntity_acc': 0.947811484336853, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.044733043760061264, 'time:timestamp_mae': 0.007339341311969541, 'case:RequestedAmount_mae': 0.10156764631921594, 'AVG_total_loss': 11.283414655111052, 'MAE_time:timestamp': 0.007141017355024815, 'MAE_case:RequestedAmount': 0.1016201302409172}
Test type odd
{'org:resource_acc': 0.9993954300880432, 'Activity_acc': 0.9591898918151855, 'org:role_acc': 0.9897218942642212, 'case:Project_acc': 0.9286578297615051, 'case:Task_acc': 0.75, 'case:OrganizationalEntity_acc': 0.9431681036949158, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03174123540520668, 'time:timestamp_mae': 0.006847506346689029, 'case:RequestedAmount_mae': 0.05946036699143323, 'AVG_total_loss': 11.554417139474852, 'MAE_time:timestamp': 0.006714316084980965, 'MAE_case:RequestedAmount': 0.05900857225060463}
Test type window
{'org:resource_acc': 0.9997873306274414, 'Activity_acc': 0.9449170231819153, 'org:role_acc': 0.9936197400093079, 'case:Project_acc': 0.9304550886154175, 'case:Task_acc': 0.7526584267616272, 'case:OrganizationalEntity_acc': 0.9451297521591187, 'case:Activity_acc': 1.0, 'case:RfpNumber_acc': 0.03998298570513725, 'time:timestamp_mae': 0.006535585080696778, 'case:RequestedAmount_mae': 0.1008132750337774, 'AVG_total_loss': 11.627087217057124, 'MAE_time:timestamp': 0.0062986500561237335, 'MAE_case:RequestedAmount': 0.10082554817199707}
Test type random
{'org:resource_acc': 0.9302638173103333, 'Activity_acc': 0.8198707103729248, 'org:role_acc': 0.8737210035324097, 'case:Project_acc': 0.8247172236442566, 'case:Task_acc': 0.752896785736084, 'case:OrganizationalEntity_acc': 0.8535271286964417, 'case:Activity_acc': 0.969574511051178, 'case:RfpNumber_acc': 0.04132695868611336, 'time:timestamp_mae': 0.007564896082674915, 'case:RequestedAmount_mae': 0.2988248575817455, 'AVG_total_loss': 13.200678930152208, 'MAE_time:timestamp': 0.007357696071267128, 'MAE_case:RequestedAmount': 0.2987363040447235}
Test type attr_level
{'org:resource_acc': 0.9935570359230042, 'Activity_acc': 0.9127675890922546, 'org:role_acc': 0.9700424671173096, 'case:Project_acc': 0.7948993444442749, 'case:Task_acc': 0.7584527730941772, 'case:OrganizationalEntity_acc': 0.8299465179443359, 'case:Activity_acc': 0.9697794914245605, 'case:RfpNumber_acc': 0.038687970489263535, 'time:timestamp_mae': 0.006764877799221061, 'case:RequestedAmount_mae': 0.3877382549372586, 'AVG_total_loss': 13.13495007906617, 'MAE_time:timestamp': 0.006593592930585146, 'MAE_case:RequestedAmount': 0.38703933358192444}
even
                                    mean       std
org:resource_acc                0.999784  0.000239
Activity_acc                    0.966691  0.003219
org:role_acc                    0.992304  0.001402
case:Project_acc                0.936412  0.007472
case:Task_acc                   0.755604  0.001520
case:OrganizationalEntity_acc   0.946368  0.013041
case:Activity_acc               1.000000  0.000000
case:RfpNumber_acc              0.044733  0.000000
time:timestamp_mae              0.006991  0.001037
case:RequestedAmount_mae        0.076305  0.022148
AVG_total_loss                 11.193622  0.206809
MAE_time:timestamp              0.006795  0.001024
MAE_case:RequestedAmount        0.076350  0.022109
odd
                                    mean       std
org:resource_acc                0.999395  0.000000
Activity_acc                    0.966264  0.015577
org:role_acc                    0.986578  0.011779
case:Project_acc                0.933283  0.006134
case:Task_acc                   0.752207  0.002285
case:OrganizationalEntity_acc   0.942261  0.013733
case:Activity_acc               1.000000  0.000000
case:RfpNumber_acc              0.031741  0.000000
time:timestamp_mae              0.007260  0.001080
case:RequestedAmount_mae        0.062943  0.021384
AVG_total_loss                 11.457125  0.232272
MAE_time:timestamp              0.007112  0.001038
MAE_case:RequestedAmount        0.062870  0.021381
window
                                    mean       std
org:resource_acc                0.998320  0.001175
Activity_acc                    0.950702  0.016147
org:role_acc                    0.990855  0.002224
case:Project_acc                0.926180  0.013758
case:Task_acc                   0.753892  0.001337
case:OrganizationalEntity_acc   0.937686  0.012887
case:Activity_acc               1.000000  0.000000
case:RfpNumber_acc              0.039983  0.000000
time:timestamp_mae              0.007691  0.001384
case:RequestedAmount_mae        0.107171  0.029300
AVG_total_loss                 11.536958  0.184601
MAE_time:timestamp              0.007470  0.001357
MAE_case:RequestedAmount        0.107375  0.029398
random
                                    mean       std
org:resource_acc                0.917771  0.023186
Activity_acc                    0.813813  0.021358
org:role_acc                    0.879079  0.014722
case:Project_acc                0.834518  0.022091
case:Task_acc                   0.753975  0.000942
case:OrganizationalEntity_acc   0.847927  0.019444
case:Activity_acc               0.978083  0.009087
case:RfpNumber_acc              0.041327  0.000000
time:timestamp_mae              0.007807  0.000585
case:RequestedAmount_mae        0.267151  0.039715
AVG_total_loss                 13.193922  0.182801
MAE_time:timestamp              0.007603  0.000591
MAE_case:RequestedAmount        0.267183  0.039751
attr_level
                                    mean       std
org:resource_acc                0.991329  0.003461
Activity_acc                    0.919455  0.008418
org:role_acc                    0.967444  0.005368
case:Project_acc                0.811919  0.023466
case:Task_acc                   0.758507  0.001882
case:OrganizationalEntity_acc   0.832995  0.030449
case:Activity_acc               0.970215  0.010058
case:RfpNumber_acc              0.037987  0.001310
time:timestamp_mae              0.007769  0.001264
case:RequestedAmount_mae        0.295240  0.043401
AVG_total_loss                 12.886929  0.282929
MAE_time:timestamp              0.007622  0.001290
MAE_case:RequestedAmount        0.294827  0.043347